#ifndef FRONTEND_MENUSCREENS_SAFEHOUSE_CUSTOMIZE_CUSTOMIZEENTRYPOINT_H
#define FRONTEND_MENUSCREENS_SAFEHOUSE_CUSTOMIZE_CUSTOMIZEENTRYPOINT_H

#ifdef EA_PRAGMA_ONCE_SUPPORTED
#pragma once
#endif

enum eCustomizeEntryPoint {
    CEP_GAMEPLAY = 0,
    CEP_MAIN_MENU = 1,
    CEP_ONLINE_MENU = 2,
};

#endif
