#include "Speed/Indep/Src/EAXSound/snd_gen/copspeech.hpp"

namespace Csis {
InterfaceId AcknowledgeId = {"Acknowledge", 0x5BA7, 0x2E86};
InterfaceId Setup_SpotterId = {"Setup_Spotter", 0x5BA7, 0x17C9};
InterfaceId Setup_SpotterWantedId = {"Setup_SpotterWanted", 0x5BA7, 0x47C7};
InterfaceId Setup_SpotterReplyId = {"Setup_SpotterReply", 0x5BA7, 0x0369};
InterfaceId Setup_AttmptVehStpId = {"Setup_AttmptVehStp", 0x5BA7, 0x668C};
InterfaceId Setup_DispGoAheadId = {"Setup_DispGoAhead", 0x5BA7, 0x17F9};
InterfaceId Setup_PrimaryEngageId = {"Setup_PrimaryEngage", 0x5BA7, 0x0A49};
InterfaceId Setup_InitPursuitId = {"Setup_InitPursuit", 0x5BA7, 0x1418};
InterfaceId Setup_SuspectConfirmedId = {"Setup_SuspectConfirmed", 0x5BA7, 0x4CBF};
InterfaceId Setup_ReInitPursuitId = {"Setup_ReInitPursuit", 0x5BA7, 0x4F90};
InterfaceId Setup_VehicleReportId = {"Setup_VehicleReport", 0x5BA7, 0x466D};
InterfaceId Setup_VehicleReportTagId = {"Setup_VehicleReportTag", 0x5BA7, 0x5E34};
InterfaceId Setup_DispVehDescripId = {"Setup_DispVehDescrip", 0x5BA7, 0x2FDF};
InterfaceId Setup_DispVehDescripVinylsId = {"Setup_DispVehDescripVinyls", 0x5BA7, 0x73EC};
InterfaceId Setup_DispNoVehDescripId = {"Setup_DispNoVehDescrip", 0x5BA7, 0x6555};
InterfaceId Setup_DispCustPaintId = {"Setup_DispCustPaint", 0x5BA7, 0x05C4};
InterfaceId Setup_MoreDetailsId = {"Setup_MoreDetails", 0x5BA7, 0x40A4};
InterfaceId Setup_LocationReportId = {"Setup_LocationReport", 0x5BA7, 0x7048};
InterfaceId Setup_BullhornPrefixId = {"Setup_BullhornPrefix", 0x5BA7, 0x5893};
InterfaceId Setup_BullhornId = {"Setup_Bullhorn", 0x5BA7, 0x5E0A};
InterfaceId Setup_SelfStrategyId = {"Setup_SelfStrategy", 0x5BA7, 0x3A53};
InterfaceId Setup_InitialCallForBUId = {"Setup_InitialCallForBU", 0x5BA7, 0x154B};
InterfaceId Setup_InitialCallForBU_MSId = {"Setup_InitialCallForBU_MS", 0x5BA7, 0x23E5};
InterfaceId Backup_CallForBUId = {"Backup_CallForBU", 0x5BA7, 0x398D};
InterfaceId Backup_UnitBUReplyId = {"Backup_UnitBUReply", 0x5BA7, 0x05D5};
InterfaceId Backup_DispBackupReplyId = {"Backup_DispBackupReply", 0x5BA7, 0x5C2F};
InterfaceId Backup_CallForSwarmingId = {"Backup_CallForSwarming", 0x5BA7, 0x5B23};
InterfaceId Backup_DispBUETAId = {"Backup_DispBUETA", 0x5BA7, 0x3C9E};
InterfaceId Backup_DispHeliBUETAId = {"Backup_DispHeliBUETA", 0x5BA7, 0x028D};
InterfaceId Backup_BUReminderId = {"Backup_BUReminder", 0x5BA7, 0x11A9};
InterfaceId Backup_NegativeBUReplyId = {"Backup_NegativeBUReply", 0x5BA7, 0x29E8};
InterfaceId Backup_DispBackupUpdateId = {"Backup_DispBackupUpdate", 0x5BA7, 0x70B2};
InterfaceId Backup_BUArrivesId = {"Backup_BUArrives", 0x5BA7, 0x4F76};
InterfaceId StaticRoadblock_CallForRBId = {"StaticRoadblock_CallForRB", 0x5BA7, 0x7D0E};
InterfaceId StaticRoadblock_RBReminderId = {"StaticRoadblock_RBReminder", 0x5BA7, 0x45D5};
InterfaceId StaticRoadblock_NegativeRBReplyId = {"StaticRoadblock_NegativeRBReply", 0x5BA7, 0x0955};
InterfaceId StaticRoadblock_DispRBReplyId = {"StaticRoadblock_DispRBReply", 0x5BA7, 0x1D9A};
InterfaceId StaticRoadblock_DispRBUpdateId = {"StaticRoadblock_DispRBUpdate", 0x5BA7, 0x7B7F};
InterfaceId StaticRoadblock_PursuitApproachingId = {"StaticRoadblock_PursuitApproaching", 0x5BA7, 0x58B5};
InterfaceId StaticRoadblock_RBApproachId = {"StaticRoadblock_RBApproach", 0x5BA7, 0x6AF1};
InterfaceId StaticRoadblock_RBEngageId = {"StaticRoadblock_RBEngage", 0x5BA7, 0x3E19};
InterfaceId StaticRoadblock_RBAvertedId = {"StaticRoadblock_RBAverted", 0x5BA7, 0x5E18};
InterfaceId StaticRoadblock_CallForRB_subId = {"StaticRoadblock_CallForRB_sub", 0x5BA7, 0x58FF};
InterfaceId StaticRoadblock_DispSubRBId = {"StaticRoadblock_DispSubRB", 0x5BA7, 0x1CEE};
InterfaceId Projectile_CallForSafetyId = {"Projectile_CallForSafety", 0x5BA7, 0x42C8};
InterfaceId Projectile_ProjectileLaunchId = {"Projectile_ProjectileLaunch", 0x5BA7, 0x0AA7};
InterfaceId Projectile_ProjectileHitId = {"Projectile_ProjectileHit", 0x5BA7, 0x6BED};
InterfaceId Projectile_ProjectileMissId = {"Projectile_ProjectileMiss", 0x5BA7, 0x1DF2};
InterfaceId RollingStrategy_InitStrategyId = {"RollingStrategy_InitStrategy", 0x5BA7, 0x3D7C};
InterfaceId RollingStrategy_CallToPositionId = {"RollingStrategy_CallToPosition", 0x5BA7, 0x2BBC};
InterfaceId RollingStrategy_CallToPositionRemId = {"RollingStrategy_CallToPositionRem", 0x5BA7, 0x4112};
InterfaceId RollingStrategy_StrategyExecuteId = {"RollingStrategy_StrategyExecute", 0x5BA7, 0x6CB7};
InterfaceId Outcome_AnticipateFailId = {"Outcome_AnticipateFail", 0x5BA7, 0x0AF9};
InterfaceId Outcome_AnticipateSuccessId = {"Outcome_AnticipateSuccess", 0x5BA7, 0x4116};
InterfaceId Outcome_OutcomeFailId = {"Outcome_OutcomeFail", 0x5BA7, 0x72D3};
InterfaceId Outcome_StrategyResetId = {"Outcome_StrategyReset", 0x5BA7, 0x4EA0};
InterfaceId Arrest_BullhornArrestId = {"Arrest_BullhornArrest", 0x5BA7, 0x1AB5};
InterfaceId Arrest_ArrestId = {"Arrest_Arrest", 0x5BA7, 0x7925};
InterfaceId Arrest_DispArrestReplyId = {"Arrest_DispArrestReply", 0x5BA7, 0x6C90};
InterfaceId AnytimeEvents_CollisionWorldId = {"AnytimeEvents_CollisionWorld", 0x5BA7, 0x6D79};
InterfaceId AnytimeEvents_CollWorld_CiviId = {"AnytimeEvents_CollWorld_Civi", 0x5BA7, 0x5569};
InterfaceId AnytimeEvents_CollWorld_SpinId = {"AnytimeEvents_CollWorld_Spin", 0x5BA7, 0x6378};
InterfaceId AnytimeEvents_CollWorld_AirId = {"AnytimeEvents_CollWorld_Air", 0x5BA7, 0x352F};
InterfaceId AnytimeEvents_CollWorld_FlipId = {"AnytimeEvents_CollWorld_Flip", 0x5BA7, 0x2DC0};
InterfaceId AnytimeEvents_DispPursuitUpdateId = {"AnytimeEvents_DispPursuitUpdate", 0x5BA7, 0x18EA};
InterfaceId AnytimeEvents_PursuitUpdateRepId = {"AnytimeEvents_PursuitUpdateRep", 0x5BA7, 0x795D};
InterfaceId AnytimeEvents_Disp911ReportId = {"AnytimeEvents_Disp911Report", 0x5BA7, 0x5E7B};
InterfaceId AnytimeEvents_Disp911CsPntId = {"AnytimeEvents_Disp911CsPnt", 0x5BA7, 0x19BC};
InterfaceId AnytimeEvents_Disp911NoDescripId = {"AnytimeEvents_Disp911NoDescrip", 0x5BA7, 0x1D71};
InterfaceId AnytimeEvents_Unit911ReplyId = {"AnytimeEvents_Unit911Reply", 0x5BA7, 0x383D};
InterfaceId AnytimeEvents_SuspectUTurnId = {"AnytimeEvents_SuspectUTurn", 0x5BA7, 0x72C0};
InterfaceId AnytimeEvents_SuspectOutrunId = {"AnytimeEvents_SuspectOutrun", 0x5BA7, 0x4847};
InterfaceId AnytimeEvents_LostVisualId = {"AnytimeEvents_LostVisual", 0x5BA7, 0x3DFC};
InterfaceId AnytimeEvents_RegainVisualId = {"AnytimeEvents_RegainVisual", 0x5BA7, 0x51D8};
InterfaceId AnytimeEvents_LostSuspectId = {"AnytimeEvents_LostSuspect", 0x5BA7, 0x34A4};
InterfaceId AnytimeEvents_DispBreakAwayId = {"AnytimeEvents_DispBreakAway", 0x5BA7, 0x54FC};
InterfaceId AnytimeEvents_DispTimeExpiredId = {"AnytimeEvents_DispTimeExpired", 0x5BA7, 0x784A};
InterfaceId AnytimeEvents_DispPursuitEscalationId = {"AnytimeEvents_DispPursuitEscalation", 0x5BA7, 0x2701};
InterfaceId AnytimeEvents_DispPursEscGenId = {"AnytimeEvents_DispPursEscGen", 0x5BA7, 0x6BAC};
InterfaceId AnytimeEvents_UnitDisabledId = {"AnytimeEvents_UnitDisabled", 0x5BA7, 0x4002};
InterfaceId AnytimeEvents_CallForEVId = {"AnytimeEvents_CallForEV", 0x5BA7, 0x216B};
InterfaceId AnytimeEvents_DispEVReplyId = {"AnytimeEvents_DispEVReply", 0x5BA7, 0x7BCE};
InterfaceId AnytimeEvents_IntentToRamId = {"AnytimeEvents_IntentToRam", 0x5BA7, 0x6C5E};
InterfaceId AnytimeEvents_BailoutId = {"AnytimeEvents_Bailout", 0x5BA7, 0x49F3};
InterfaceId AnytimeEvents_BailoutDenyId = {"AnytimeEvents_BailoutDeny", 0x5BA7, 0x416F};
InterfaceId AnytimeEvents_FocusChangeId = {"AnytimeEvents_FocusChange", 0x5BA7, 0x39B1};
InterfaceId AnytimeEvents_SuspectBehaviourId = {"AnytimeEvents_SuspectBehaviour", 0x5BA7, 0x688B};
InterfaceId AnytimeEvents_DriverHistoryId = {"AnytimeEvents_DriverHistory", 0x5BA7, 0x689E};
InterfaceId AnytimeEvents_OffroadMomentId = {"AnytimeEvents_OffroadMoment", 0x5BA7, 0x7B7E};
InterfaceId AnytimeEvents_SpottedId = {"AnytimeEvents_Spotted", 0x5BA7, 0x0CB3};
InterfaceId AnytimeEvents_SuspectBrakeId = {"AnytimeEvents_SuspectBrake", 0x5BA7, 0x54F4};
InterfaceId AnytimeEvents_WeatherReportId = {"AnytimeEvents_WeatherReport", 0x5BA7, 0x7F43};
InterfaceId AnytimeEvents_HeatJumpId = {"AnytimeEvents_HeatJump", 0x5BA7, 0x715F};
InterfaceId AnytimeEvents_DirectionHighId = {"AnytimeEvents_DirectionHigh", 0x5BA7, 0x6373};
InterfaceId AnytimeEvents_DispJurisShiftId = {"AnytimeEvents_DispJurisShift", 0x5BA7, 0x0C76};
InterfaceId HeliSpecific_HeliSelfStrategyId = {"HeliSpecific_HeliSelfStrategy", 0x5BA7, 0x2A4F};
InterfaceId HeliSpecific_HeliLostVisualId = {"HeliSpecific_HeliLostVisual", 0x5BA7, 0x0744};
InterfaceId HeliSpecific_HeliIntentToBailId = {"HeliSpecific_HeliIntentToBail", 0x5BA7, 0x4FED};
InterfaceId HeliSpecific_HeliBailoutId = {"HeliSpecific_HeliBailout", 0x5BA7, 0x2394};
InterfaceId HeliSpecific_HeliSwarmingId = {"HeliSpecific_HeliSwarming", 0x5BA7, 0x2274};
InterfaceId HeliSpecific_HeliSpotterId = {"HeliSpecific_HeliSpotter", 0x5BA7, 0x35F5};
InterfaceId HeliSpecific_HeliHazardAlertId = {"HeliSpecific_HeliHazardAlert", 0x5BA7, 0x4AFB};
InterfaceId HeliSpecific_HeliQuadrentId = {"HeliSpecific_HeliQuadrent", 0x5BA7, 0x4F58};
InterfaceId HeliSpecific_HeliQuadrentMovingId = {"HeliSpecific_HeliQuadrentMoving", 0x5BA7, 0x07F9};
InterfaceId HeliSpecific_HeliBullhornArrestId = {"HeliSpecific_HeliBullhornArrest", 0x5BA7, 0x0D4B};
InterfaceId E3_Events_E3_SetupId = {"E3_Events_E3_Setup", 0x5BA7, 0x16B2};
InterfaceId Interrupts_InterruptId = {"Interrupts_Interrupt", 0x5BA7, 0x1771};
InterfaceId Interrupts_InterruptRamId = {"Interrupts_InterruptRam", 0x5BA7, 0x5E3B};
InterfaceId Interrupts_InterruptRam_REId = {"Interrupts_InterruptRam_RE", 0x5BA7, 0x13B3};
InterfaceId Interrupts_InterruptRam_HOId = {"Interrupts_InterruptRam_HO", 0x5BA7, 0x6FB0};
InterfaceId Interrupts_InterruptRam_SSId = {"Interrupts_InterruptRam_SS", 0x5BA7, 0x1AD3};
InterfaceId Interrupts_InterruptRam_TBId = {"Interrupts_InterruptRam_TB", 0x5BA7, 0x327B};
InterfaceId Interrupts_InterruptRamHighId = {"Interrupts_InterruptRamHigh", 0x5BA7, 0x3FD5};
InterfaceId Interrupts_StaticInterruptId = {"Interrupts_StaticInterrupt", 0x5BA7, 0x5513};
InterfaceId Interrupts_RegainVisualInterruptId = {"Interrupts_RegainVisualInterrupt", 0x5BA7, 0x1F16};
InterfaceId CellCallId = {"CellCall", 0x5BA7, 0x107B};
InterfaceId ExtraCops_SwarmingReplyId = {"ExtraCops_SwarmingReply", 0x5BA7, 0x5B8C};
InterfaceId ExtraCops_SuperPursuitReplyId = {"ExtraCops_SuperPursuitReply", 0x5BA7, 0x2D39};
InterfaceId ExtraCops_SwarmingReplyFollowId = {"ExtraCops_SwarmingReplyFollow", 0x5BA7, 0x7675};
InterfaceId ExtraCops_QuadrentFormingId = {"ExtraCops_QuadrentForming", 0x5BA7, 0x725B};
InterfaceId ExtraCops_SuspectPossiblyGoneId = {"ExtraCops_SuspectPossiblyGone", 0x5BA7, 0x4D03};
InterfaceId ExtraCops_QuadrentMovingId = {"ExtraCops_QuadrentMoving", 0x5BA7, 0x03A9};
InterfaceId ExtraCops_OtherLeadId = {"ExtraCops_OtherLead", 0x5BA7, 0x5928};
InterfaceId ExtraCops_PossibleSuspectId = {"ExtraCops_PossibleSuspect", 0x5BA7, 0x708A};
InterfaceId ExtraCops_WrongSuspectId = {"ExtraCops_WrongSuspect", 0x5BA7, 0x0F86};
InterfaceId ExtraCops_SuspectGoneId = {"ExtraCops_SuspectGone", 0x5BA7, 0x4596};
InterfaceId ExtraCops_RBWarningId = {"ExtraCops_RBWarning", 0x5BA7, 0x633F};
InterfaceId ExtraCops_RBPositionId = {"ExtraCops_RBPosition", 0x5BA7, 0x72D8};
InterfaceId ExtraCops_ExtraRBEngageId = {"ExtraCops_ExtraRBEngage", 0x5BA7, 0x0D4E};
InterfaceId ExtraCops_ExtraRBAvertedId = {"ExtraCops_ExtraRBAverted", 0x5BA7, 0x2780};
InterfaceId Cross_CrossBUReplyId = {"Cross_CrossBUReply", 0x5BA7, 0x3A3A};
InterfaceId Cross_CrossFailReplyId = {"Cross_CrossFailReply", 0x5BA7, 0x7D92};
InterfaceId Cross_CrossRBFailReplyId = {"Cross_CrossRBFailReply", 0x5BA7, 0x2D29};
InterfaceId Cross_CrossPursuitEscId = {"Cross_CrossPursuitEsc", 0x5BA7, 0x71B7};
InterfaceId Cross_CrossSelfStrategyId = {"Cross_CrossSelfStrategy", 0x5BA7, 0x5684};
InterfaceId Cross_CrossMultiStrategyId = {"Cross_CrossMultiStrategy", 0x5BA7, 0x6559};
InterfaceId Cross_CrossBailoutDeny_subId = {"Cross_CrossBailoutDeny_sub", 0x5BA7, 0x4D12};
InterfaceId D_DayId = {"D_Day", 0x5BA7, 0x2ECC};
InterfaceId DispIntroRaceId = {"DispIntroRace", 0x5BA7, 0x2722};
InterfaceId NIS_Select_StartId = {"NIS_Select_Start", 0x0BE4, 0x67D1};
InterfaceId NIS_Select_EndId = {"NIS_Select_End", 0x0BE4, 0x4888};
InterfaceId SoundFX_SelectId = {"SoundFX_Select", 0x0BE4, 0x2052};
InterfaceId NIS_Select_BlacklistId = {"NIS_Select_Blacklist", 0x0BE4, 0x3B39};

FunctionHandle gAcknowledgeHandle;
FunctionHandle gSetup_SpotterHandle;
FunctionHandle gSetup_SpotterWantedHandle;
FunctionHandle gSetup_SpotterReplyHandle;
FunctionHandle gSetup_AttmptVehStpHandle;
FunctionHandle gSetup_DispGoAheadHandle;
FunctionHandle gSetup_PrimaryEngageHandle;
FunctionHandle gSetup_InitPursuitHandle;
FunctionHandle gSetup_SuspectConfirmedHandle;
FunctionHandle gSetup_ReInitPursuitHandle;
FunctionHandle gSetup_VehicleReportHandle;
FunctionHandle gSetup_VehicleReportTagHandle;
FunctionHandle gSetup_DispVehDescripHandle;
FunctionHandle gSetup_DispVehDescripVinylsHandle;
FunctionHandle gSetup_DispNoVehDescripHandle;
FunctionHandle gSetup_DispCustPaintHandle;
FunctionHandle gSetup_MoreDetailsHandle;
FunctionHandle gSetup_LocationReportHandle;
FunctionHandle gSetup_BullhornPrefixHandle;
FunctionHandle gSetup_BullhornHandle;
FunctionHandle gSetup_SelfStrategyHandle;
FunctionHandle gSetup_InitialCallForBUHandle;
FunctionHandle gSetup_InitialCallForBU_MSHandle;
FunctionHandle gBackup_CallForBUHandle;
FunctionHandle gBackup_UnitBUReplyHandle;
FunctionHandle gBackup_DispBackupReplyHandle;
FunctionHandle gBackup_CallForSwarmingHandle;
FunctionHandle gBackup_DispBUETAHandle;
FunctionHandle gBackup_DispHeliBUETAHandle;
FunctionHandle gBackup_BUReminderHandle;
FunctionHandle gBackup_NegativeBUReplyHandle;
FunctionHandle gBackup_DispBackupUpdateHandle;
FunctionHandle gBackup_BUArrivesHandle;
FunctionHandle gStaticRoadblock_CallForRBHandle;
FunctionHandle gStaticRoadblock_RBReminderHandle;
FunctionHandle gStaticRoadblock_NegativeRBReplyHandle;
FunctionHandle gStaticRoadblock_DispRBReplyHandle;
FunctionHandle gStaticRoadblock_DispRBUpdateHandle;
FunctionHandle gStaticRoadblock_PursuitApproachingHandle;
FunctionHandle gStaticRoadblock_RBApproachHandle;
FunctionHandle gStaticRoadblock_RBEngageHandle;
FunctionHandle gStaticRoadblock_RBAvertedHandle;
FunctionHandle gStaticRoadblock_CallForRB_subHandle;
FunctionHandle gStaticRoadblock_DispSubRBHandle;
FunctionHandle gProjectile_CallForSafetyHandle;
FunctionHandle gProjectile_ProjectileLaunchHandle;
FunctionHandle gProjectile_ProjectileHitHandle;
FunctionHandle gProjectile_ProjectileMissHandle;
FunctionHandle gRollingStrategy_InitStrategyHandle;
FunctionHandle gRollingStrategy_CallToPositionHandle;
FunctionHandle gRollingStrategy_CallToPositionRemHandle;
FunctionHandle gRollingStrategy_StrategyExecuteHandle;
FunctionHandle gOutcome_AnticipateFailHandle;
FunctionHandle gOutcome_AnticipateSuccessHandle;
FunctionHandle gOutcome_OutcomeFailHandle;
FunctionHandle gOutcome_StrategyResetHandle;
FunctionHandle gArrest_BullhornArrestHandle;
FunctionHandle gArrest_ArrestHandle;
FunctionHandle gArrest_DispArrestReplyHandle;
FunctionHandle gAnytimeEvents_CollisionWorldHandle;
FunctionHandle gAnytimeEvents_CollWorld_CiviHandle;
FunctionHandle gAnytimeEvents_CollWorld_SpinHandle;
FunctionHandle gAnytimeEvents_CollWorld_AirHandle;
FunctionHandle gAnytimeEvents_CollWorld_FlipHandle;
FunctionHandle gAnytimeEvents_DispPursuitUpdateHandle;
FunctionHandle gAnytimeEvents_PursuitUpdateRepHandle;
FunctionHandle gAnytimeEvents_Disp911ReportHandle;
FunctionHandle gAnytimeEvents_Disp911CsPntHandle;
FunctionHandle gAnytimeEvents_Disp911NoDescripHandle;
FunctionHandle gAnytimeEvents_Unit911ReplyHandle;
FunctionHandle gAnytimeEvents_SuspectUTurnHandle;
FunctionHandle gAnytimeEvents_SuspectOutrunHandle;
FunctionHandle gAnytimeEvents_LostVisualHandle;
FunctionHandle gAnytimeEvents_RegainVisualHandle;
FunctionHandle gAnytimeEvents_LostSuspectHandle;
FunctionHandle gAnytimeEvents_DispBreakAwayHandle;
FunctionHandle gAnytimeEvents_DispTimeExpiredHandle;
FunctionHandle gAnytimeEvents_DispPursuitEscalationHandle;
FunctionHandle gAnytimeEvents_DispPursEscGenHandle;
FunctionHandle gAnytimeEvents_UnitDisabledHandle;
FunctionHandle gAnytimeEvents_CallForEVHandle;
FunctionHandle gAnytimeEvents_DispEVReplyHandle;
FunctionHandle gAnytimeEvents_IntentToRamHandle;
FunctionHandle gAnytimeEvents_BailoutHandle;
FunctionHandle gAnytimeEvents_BailoutDenyHandle;
FunctionHandle gAnytimeEvents_FocusChangeHandle;
FunctionHandle gAnytimeEvents_SuspectBehaviourHandle;
FunctionHandle gAnytimeEvents_DriverHistoryHandle;
FunctionHandle gAnytimeEvents_OffroadMomentHandle;
FunctionHandle gAnytimeEvents_SpottedHandle;
FunctionHandle gAnytimeEvents_SuspectBrakeHandle;
FunctionHandle gAnytimeEvents_WeatherReportHandle;
FunctionHandle gAnytimeEvents_HeatJumpHandle;
FunctionHandle gAnytimeEvents_DirectionHighHandle;
FunctionHandle gAnytimeEvents_DispJurisShiftHandle;
FunctionHandle gHeliSpecific_HeliSelfStrategyHandle;
FunctionHandle gHeliSpecific_HeliLostVisualHandle;
FunctionHandle gHeliSpecific_HeliIntentToBailHandle;
FunctionHandle gHeliSpecific_HeliBailoutHandle;
FunctionHandle gHeliSpecific_HeliSwarmingHandle;
FunctionHandle gHeliSpecific_HeliSpotterHandle;
FunctionHandle gHeliSpecific_HeliHazardAlertHandle;
FunctionHandle gHeliSpecific_HeliQuadrentHandle;
FunctionHandle gHeliSpecific_HeliQuadrentMovingHandle;
FunctionHandle gHeliSpecific_HeliBullhornArrestHandle;
FunctionHandle gE3_Events_E3_SetupHandle;
FunctionHandle gInterrupts_InterruptHandle;
FunctionHandle gInterrupts_InterruptRamHandle;
FunctionHandle gInterrupts_InterruptRam_REHandle;
FunctionHandle gInterrupts_InterruptRam_HOHandle;
FunctionHandle gInterrupts_InterruptRam_SSHandle;
FunctionHandle gInterrupts_InterruptRam_TBHandle;
FunctionHandle gInterrupts_InterruptRamHighHandle;
FunctionHandle gInterrupts_StaticInterruptHandle;
FunctionHandle gInterrupts_RegainVisualInterruptHandle;
FunctionHandle gCellCallHandle;
FunctionHandle gExtraCops_SwarmingReplyHandle;
FunctionHandle gExtraCops_SuperPursuitReplyHandle;
FunctionHandle gExtraCops_SwarmingReplyFollowHandle;
FunctionHandle gExtraCops_QuadrentFormingHandle;
FunctionHandle gExtraCops_SuspectPossiblyGoneHandle;
FunctionHandle gExtraCops_QuadrentMovingHandle;
FunctionHandle gExtraCops_OtherLeadHandle;
FunctionHandle gExtraCops_PossibleSuspectHandle;
FunctionHandle gExtraCops_WrongSuspectHandle;
FunctionHandle gExtraCops_SuspectGoneHandle;
FunctionHandle gExtraCops_RBWarningHandle;
FunctionHandle gExtraCops_RBPositionHandle;
FunctionHandle gExtraCops_ExtraRBEngageHandle;
FunctionHandle gExtraCops_ExtraRBAvertedHandle;
FunctionHandle gCross_CrossBUReplyHandle;
FunctionHandle gCross_CrossFailReplyHandle;
FunctionHandle gCross_CrossRBFailReplyHandle;
FunctionHandle gCross_CrossPursuitEscHandle;
FunctionHandle gCross_CrossSelfStrategyHandle;
FunctionHandle gCross_CrossMultiStrategyHandle;
FunctionHandle gCross_CrossBailoutDeny_subHandle;
FunctionHandle gD_DayHandle;
FunctionHandle gDispIntroRaceHandle;
extern FunctionHandle gNIS_Select_StartHandle;
extern FunctionHandle gNIS_Select_EndHandle;
extern FunctionHandle gSoundFX_SelectHandle;
extern FunctionHandle gNIS_Select_BlacklistHandle;

} // namespace Csis
