#include "Speed/Indep/Src/EAXSound/snd_gen/copspeech.hpp"

namespace Csis {
InterfaceId AcknowledgeId = {"Acknowledge", 0x5BA7, 0x2E86};
InterfaceId Setup_SpotterId = {"Setup_Spotter", 0x5BA7, 0x17C9};
InterfaceId Setup_SpotterWantedId = {"Setup_SpotterWanted", 0x5BA7, 0x47C7};
InterfaceId Setup_SpotterReplyId = {"Setup_SpotterReply", 0x5BA7, 0x0369};
InterfaceId Setup_AttmptVehStpId = {"Setup_AttmptVehStp", 0x5BA7, 0x668C};
InterfaceId Setup_DispGoAheadId = {"Setup_DispGoAhead", 0x5BA7, 0x17F9};
InterfaceId Setup_PrimaryEngageId = {"Setup_PrimaryEngage", 0x5BA7, 0x0A49};
InterfaceId Setup_InitPursuitId = {"Setup_InitPursuit", 0x5BA7, 0x1418};
InterfaceId Setup_SuspectConfirmedId = {"Setup_SuspectConfirmed", 0x5BA7, 0x4CBF};
InterfaceId Setup_ReInitPursuitId = {"Setup_ReInitPursuit", 0x5BA7, 0x4F90};
InterfaceId Setup_VehicleReportId = {"Setup_VehicleReport", 0x5BA7, 0x466D};
InterfaceId Setup_VehicleReportTagId = {"Setup_VehicleReportTag", 0x5BA7, 0x5E34};
InterfaceId Setup_DispVehDescripId = {"Setup_DispVehDescrip", 0x5BA7, 0x2FDF};
InterfaceId Setup_DispVehDescripVinylsId = {"Setup_DispVehDescripVinyls", 0x5BA7, 0x73EC};
InterfaceId Setup_DispNoVehDescripId = {"Setup_DispNoVehDescrip", 0x5BA7, 0x6555};
InterfaceId Setup_DispCustPaintId = {"Setup_DispCustPaint", 0x5BA7, 0x05C4};
InterfaceId Setup_MoreDetailsId = {"Setup_MoreDetails", 0x5BA7, 0x40A4};
InterfaceId Setup_LocationReportId = {"Setup_LocationReport", 0x5BA7, 0x7048};
InterfaceId Setup_BullhornPrefixId = {"Setup_BullhornPrefix", 0x5BA7, 0x5893};
InterfaceId Setup_BullhornId = {"Setup_Bullhorn", 0x5BA7, 0x5E0A};
InterfaceId Setup_SelfStrategyId = {"Setup_SelfStrategy", 0x5BA7, 0x3A53};
InterfaceId Setup_InitialCallForBUId = {"Setup_InitialCallForBU", 0x5BA7, 0x154B};
InterfaceId Setup_InitialCallForBU_MSId = {"Setup_InitialCallForBU_MS", 0x5BA7, 0x23E5};
InterfaceId Backup_CallForBUId = {"Backup_CallForBU", 0x5BA7, 0x398D};
InterfaceId Backup_UnitBUReplyId = {"Backup_UnitBUReply", 0x5BA7, 0x05D5};
InterfaceId Backup_DispBackupReplyId = {"Backup_DispBackupReply", 0x5BA7, 0x5C2F};
InterfaceId Backup_CallForSwarmingId = {"Backup_CallForSwarming", 0x5BA7, 0x5B23};
InterfaceId Backup_DispBUETAId = {"Backup_DispBUETA", 0x5BA7, 0x3C9E};
InterfaceId Backup_DispHeliBUETAId = {"Backup_DispHeliBUETA", 0x5BA7, 0x028D};
InterfaceId Backup_BUReminderId = {"Backup_BUReminder", 0x5BA7, 0x11A9};
InterfaceId Backup_NegativeBUReplyId = {"Backup_NegativeBUReply", 0x5BA7, 0x29E8};
InterfaceId Backup_DispBackupUpdateId = {"Backup_DispBackupUpdate", 0x5BA7, 0x70B2};
InterfaceId Backup_BUArrivesId = {"Backup_BUArrives", 0x5BA7, 0x4F76};
InterfaceId StaticRoadblock_CallForRBId = {"StaticRoadblock_CallForRB", 0x5BA7, 0x7D0E};
InterfaceId StaticRoadblock_RBReminderId = {"StaticRoadblock_RBReminder", 0x5BA7, 0x45D5};
InterfaceId StaticRoadblock_NegativeRBReplyId = {"StaticRoadblock_NegativeRBReply", 0x5BA7, 0x0955};
InterfaceId StaticRoadblock_DispRBReplyId = {"StaticRoadblock_DispRBReply", 0x5BA7, 0x1D9A};
InterfaceId StaticRoadblock_DispRBUpdateId = {"StaticRoadblock_DispRBUpdate", 0x5BA7, 0x7B7F};
InterfaceId StaticRoadblock_PursuitApproachingId = {"StaticRoadblock_PursuitApproaching", 0x5BA7, 0x58B5};
InterfaceId StaticRoadblock_RBApproachId = {"StaticRoadblock_RBApproach", 0x5BA7, 0x6AF1};
InterfaceId StaticRoadblock_RBEngageId = {"StaticRoadblock_RBEngage", 0x5BA7, 0x3E19};
InterfaceId StaticRoadblock_RBAvertedId = {"StaticRoadblock_RBAverted", 0x5BA7, 0x5E18};
InterfaceId StaticRoadblock_CallForRB_subId = {"StaticRoadblock_CallForRB_sub", 0x5BA7, 0x58FF};
InterfaceId StaticRoadblock_DispSubRBId = {"StaticRoadblock_DispSubRB", 0x5BA7, 0x1CEE};
InterfaceId Projectile_CallForSafetyId = {"Projectile_CallForSafety", 0x5BA7, 0x42C8};
InterfaceId Projectile_ProjectileLaunchId = {"Projectile_ProjectileLaunch", 0x5BA7, 0x0AA7};
InterfaceId Projectile_ProjectileHitId = {"Projectile_ProjectileHit", 0x5BA7, 0x6BED};
InterfaceId Projectile_ProjectileMissId = {"Projectile_ProjectileMiss", 0x5BA7, 0x1DF2};
InterfaceId RollingStrategy_InitStrategyId = {"RollingStrategy_InitStrategy", 0x5BA7, 0x3D7C};
InterfaceId RollingStrategy_CallToPositionId = {"RollingStrategy_CallToPosition", 0x5BA7, 0x2BBC};
InterfaceId RollingStrategy_CallToPositionRemId = {"RollingStrategy_CallToPositionRem", 0x5BA7, 0x4112};
InterfaceId RollingStrategy_StrategyExecuteId = {"RollingStrategy_StrategyExecute", 0x5BA7, 0x6CB7};
InterfaceId Outcome_AnticipateFailId = {"Outcome_AnticipateFail", 0x5BA7, 0x0AF9};
InterfaceId Outcome_AnticipateSuccessId = {"Outcome_AnticipateSuccess", 0x5BA7, 0x4116};
InterfaceId Outcome_OutcomeFailId = {"Outcome_OutcomeFail", 0x5BA7, 0x72D3};
InterfaceId Outcome_StrategyResetId = {"Outcome_StrategyReset", 0x5BA7, 0x4EA0};
InterfaceId Arrest_BullhornArrestId = {"Arrest_BullhornArrest", 0x5BA7, 0x1AB5};
InterfaceId Arrest_ArrestId = {"Arrest_Arrest", 0x5BA7, 0x7925};
InterfaceId Arrest_DispArrestReplyId = {"Arrest_DispArrestReply", 0x5BA7, 0x6C90};
InterfaceId AnytimeEvents_CollisionWorldId = {"AnytimeEvents_CollisionWorld", 0x5BA7, 0x6D79};
InterfaceId AnytimeEvents_CollWorld_CiviId = {"AnytimeEvents_CollWorld_Civi", 0x5BA7, 0x5569};
InterfaceId AnytimeEvents_CollWorld_SpinId = {"AnytimeEvents_CollWorld_Spin", 0x5BA7, 0x6378};
InterfaceId AnytimeEvents_CollWorld_AirId = {"AnytimeEvents_CollWorld_Air", 0x5BA7, 0x352F};
InterfaceId AnytimeEvents_CollWorld_FlipId = {"AnytimeEvents_CollWorld_Flip", 0x5BA7, 0x2DC0};
InterfaceId AnytimeEvents_DispPursuitUpdateId = {"AnytimeEvents_DispPursuitUpdate", 0x5BA7, 0x18EA};
InterfaceId AnytimeEvents_PursuitUpdateRepId = {"AnytimeEvents_PursuitUpdateRep", 0x5BA7, 0x795D};
InterfaceId AnytimeEvents_Disp911ReportId = {"AnytimeEvents_Disp911Report", 0x5BA7, 0x5E7B};
InterfaceId AnytimeEvents_Disp911CsPntId = {"AnytimeEvents_Disp911CsPnt", 0x5BA7, 0x19BC};
InterfaceId AnytimeEvents_Disp911NoDescripId = {"AnytimeEvents_Disp911NoDescrip", 0x5BA7, 0x1D71};
InterfaceId AnytimeEvents_Unit911ReplyId = {"AnytimeEvents_Unit911Reply", 0x5BA7, 0x383D};
InterfaceId AnytimeEvents_SuspectUTurnId = {"AnytimeEvents_SuspectUTurn", 0x5BA7, 0x72C0};
InterfaceId AnytimeEvents_SuspectOutrunId = {"AnytimeEvents_SuspectOutrun", 0x5BA7, 0x4847};
InterfaceId AnytimeEvents_LostVisualId = {"AnytimeEvents_LostVisual", 0x5BA7, 0x3DFC};
InterfaceId AnytimeEvents_RegainVisualId = {"AnytimeEvents_RegainVisual", 0x5BA7, 0x51D8};
InterfaceId AnytimeEvents_LostSuspectId = {"AnytimeEvents_LostSuspect", 0x5BA7, 0x34A4};
InterfaceId AnytimeEvents_DispBreakAwayId = {"AnytimeEvents_DispBreakAway", 0x5BA7, 0x54FC};
InterfaceId AnytimeEvents_DispTimeExpiredId = {"AnytimeEvents_DispTimeExpired", 0x5BA7, 0x784A};
InterfaceId AnytimeEvents_DispPursuitEscalationId = {"AnytimeEvents_DispPursuitEscalation", 0x5BA7, 0x2701};
InterfaceId AnytimeEvents_DispPursEscGenId = {"AnytimeEvents_DispPursEscGen", 0x5BA7, 0x6BAC};
InterfaceId AnytimeEvents_UnitDisabledId = {"AnytimeEvents_UnitDisabled", 0x5BA7, 0x4002};
InterfaceId AnytimeEvents_CallForEVId = {"AnytimeEvents_CallForEV", 0x5BA7, 0x216B};
InterfaceId AnytimeEvents_DispEVReplyId = {"AnytimeEvents_DispEVReply", 0x5BA7, 0x7BCE};
InterfaceId AnytimeEvents_IntentToRamId = {"AnytimeEvents_IntentToRam", 0x5BA7, 0x6C5E};
InterfaceId AnytimeEvents_BailoutId = {"AnytimeEvents_Bailout", 0x5BA7, 0x49F3};
InterfaceId AnytimeEvents_BailoutDenyId = {"AnytimeEvents_BailoutDeny", 0x5BA7, 0x416F};
InterfaceId AnytimeEvents_FocusChangeId = {"AnytimeEvents_FocusChange", 0x5BA7, 0x39B1};
InterfaceId AnytimeEvents_SuspectBehaviourId = {"AnytimeEvents_SuspectBehaviour", 0x5BA7, 0x688B};
InterfaceId AnytimeEvents_DriverHistoryId = {"AnytimeEvents_DriverHistory", 0x5BA7, 0x689E};
InterfaceId AnytimeEvents_OffroadMomentId = {"AnytimeEvents_OffroadMoment", 0x5BA7, 0x7B7E};
InterfaceId AnytimeEvents_SpottedId = {"AnytimeEvents_Spotted", 0x5BA7, 0x0CB3};
InterfaceId AnytimeEvents_SuspectBrakeId = {"AnytimeEvents_SuspectBrake", 0x5BA7, 0x54F4};
InterfaceId AnytimeEvents_WeatherReportId = {"AnytimeEvents_WeatherReport", 0x5BA7, 0x7F43};
InterfaceId AnytimeEvents_HeatJumpId = {"AnytimeEvents_HeatJump", 0x5BA7, 0x715F};
InterfaceId AnytimeEvents_DirectionHighId = {"AnytimeEvents_DirectionHigh", 0x5BA7, 0x6373};
InterfaceId AnytimeEvents_DispJurisShiftId = {"AnytimeEvents_DispJurisShift", 0x5BA7, 0x0C76};
InterfaceId HeliSpecific_HeliSelfStrategyId = {"HeliSpecific_HeliSelfStrategy", 0x5BA7, 0x2A4F};
InterfaceId HeliSpecific_HeliLostVisualId = {"HeliSpecific_HeliLostVisual", 0x5BA7, 0x0744};
InterfaceId HeliSpecific_HeliIntentToBailId = {"HeliSpecific_HeliIntentToBail", 0x5BA7, 0x4FED};
InterfaceId HeliSpecific_HeliBailoutId = {"HeliSpecific_HeliBailout", 0x5BA7, 0x2394};
InterfaceId HeliSpecific_HeliSwarmingId = {"HeliSpecific_HeliSwarming", 0x5BA7, 0x2274};
InterfaceId HeliSpecific_HeliSpotterId = {"HeliSpecific_HeliSpotter", 0x5BA7, 0x35F5};
InterfaceId HeliSpecific_HeliHazardAlertId = {"HeliSpecific_HeliHazardAlert", 0x5BA7, 0x4AFB};
InterfaceId HeliSpecific_HeliQuadrentId = {"HeliSpecific_HeliQuadrent", 0x5BA7, 0x4F58};
InterfaceId HeliSpecific_HeliQuadrentMovingId = {"HeliSpecific_HeliQuadrentMoving", 0x5BA7, 0x07F9};
InterfaceId HeliSpecific_HeliBullhornArrestId = {"HeliSpecific_HeliBullhornArrest", 0x5BA7, 0x0D4B};
InterfaceId E3_Events_E3_SetupId = {"E3_Events_E3_Setup", 0x5BA7, 0x16B2};
InterfaceId Interrupts_InterruptId = {"Interrupts_Interrupt", 0x5BA7, 0x1771};
InterfaceId Interrupts_InterruptRamId = {"Interrupts_InterruptRam", 0x5BA7, 0x5E3B};
InterfaceId Interrupts_InterruptRam_REId = {"Interrupts_InterruptRam_RE", 0x5BA7, 0x13B3};
InterfaceId Interrupts_InterruptRam_HOId = {"Interrupts_InterruptRam_HO", 0x5BA7, 0x6FB0};
InterfaceId Interrupts_InterruptRam_SSId = {"Interrupts_InterruptRam_SS", 0x5BA7, 0x1AD3};
InterfaceId Interrupts_InterruptRam_TBId = {"Interrupts_InterruptRam_TB", 0x5BA7, 0x327B};
InterfaceId Interrupts_InterruptRamHighId = {"Interrupts_InterruptRamHigh", 0x5BA7, 0x3FD5};
InterfaceId Interrupts_StaticInterruptId = {"Interrupts_StaticInterrupt", 0x5BA7, 0x5513};
InterfaceId Interrupts_RegainVisualInterruptId = {"Interrupts_RegainVisualInterrupt", 0x5BA7, 0x1F16};
InterfaceId CellCallId = {"CellCall", 0x5BA7, 0x107B};
InterfaceId ExtraCops_SwarmingReplyId = {"ExtraCops_SwarmingReply", 0x5BA7, 0x5B8C};
InterfaceId ExtraCops_SuperPursuitReplyId = {"ExtraCops_SuperPursuitReply", 0x5BA7, 0x2D39};
InterfaceId ExtraCops_SwarmingReplyFollowId = {"ExtraCops_SwarmingReplyFollow", 0x5BA7, 0x7675};
InterfaceId ExtraCops_QuadrentFormingId = {"ExtraCops_QuadrentForming", 0x5BA7, 0x725B};
InterfaceId ExtraCops_SuspectPossiblyGoneId = {"ExtraCops_SuspectPossiblyGone", 0x5BA7, 0x4D03};
InterfaceId ExtraCops_QuadrentMovingId = {"ExtraCops_QuadrentMoving", 0x5BA7, 0x03A9};
InterfaceId ExtraCops_OtherLeadId = {"ExtraCops_OtherLead", 0x5BA7, 0x5928};
InterfaceId ExtraCops_PossibleSuspectId = {"ExtraCops_PossibleSuspect", 0x5BA7, 0x708A};
InterfaceId ExtraCops_WrongSuspectId = {"ExtraCops_WrongSuspect", 0x5BA7, 0x0F86};
InterfaceId ExtraCops_SuspectGoneId = {"ExtraCops_SuspectGone", 0x5BA7, 0x4596};
InterfaceId ExtraCops_RBWarningId = {"ExtraCops_RBWarning", 0x5BA7, 0x633F};
InterfaceId ExtraCops_RBPositionId = {"ExtraCops_RBPosition", 0x5BA7, 0x72D8};
InterfaceId ExtraCops_ExtraRBEngageId = {"ExtraCops_ExtraRBEngage", 0x5BA7, 0x0D4E};
InterfaceId ExtraCops_ExtraRBAvertedId = {"ExtraCops_ExtraRBAverted", 0x5BA7, 0x2780};
InterfaceId Cross_CrossBUReplyId = {"Cross_CrossBUReply", 0x5BA7, 0x3A3A};
InterfaceId Cross_CrossFailReplyId = {"Cross_CrossFailReply", 0x5BA7, 0x7D92};
InterfaceId Cross_CrossRBFailReplyId = {"Cross_CrossRBFailReply", 0x5BA7, 0x2D29};
InterfaceId Cross_CrossPursuitEscId = {"Cross_CrossPursuitEsc", 0x5BA7, 0x71B7};
InterfaceId Cross_CrossSelfStrategyId = {"Cross_CrossSelfStrategy", 0x5BA7, 0x5684};
InterfaceId Cross_CrossMultiStrategyId = {"Cross_CrossMultiStrategy", 0x5BA7, 0x6559};
InterfaceId Cross_CrossBailoutDeny_subId = {"Cross_CrossBailoutDeny_sub", 0x5BA7, 0x4D12};
InterfaceId D_DayId = {"D_Day", 0x5BA7, 0x2ECC};
InterfaceId DispIntroRaceId = {"DispIntroRace", 0x5BA7, 0x2722};
InterfaceId NIS_Select_StartId = {"NIS_Select_Start", 0x0BE4, 0x67D1};
InterfaceId NIS_Select_EndId = {"NIS_Select_End", 0x0BE4, 0x4888};
InterfaceId SoundFX_SelectId = {"SoundFX_Select", 0x0BE4, 0x2052};
InterfaceId NIS_Select_BlacklistId = {"NIS_Select_Blacklist", 0x0BE4, 0x3B39};

FunctionHandle gAcknowledgeHandle;
FunctionHandle gSetup_SpotterHandle;
FunctionHandle gSetup_SpotterWantedHandle;
FunctionHandle gSetup_SpotterReplyHandle;
FunctionHandle gSetup_AttmptVehStpHandle;
FunctionHandle gSetup_DispGoAheadHandle;
FunctionHandle gSetup_PrimaryEngageHandle;
FunctionHandle gSetup_InitPursuitHandle;
FunctionHandle gSetup_SuspectConfirmedHandle;
FunctionHandle gSetup_ReInitPursuitHandle;
FunctionHandle gSetup_VehicleReportHandle;
FunctionHandle gSetup_VehicleReportTagHandle;
FunctionHandle gSetup_DispVehDescripHandle;
FunctionHandle gSetup_DispVehDescripVinylsHandle;
FunctionHandle gSetup_DispNoVehDescripHandle;
FunctionHandle gSetup_DispCustPaintHandle;
FunctionHandle gSetup_MoreDetailsHandle;
FunctionHandle gSetup_LocationReportHandle;
FunctionHandle gSetup_BullhornPrefixHandle;
FunctionHandle gSetup_BullhornHandle;
FunctionHandle gSetup_SelfStrategyHandle;
FunctionHandle gSetup_InitialCallForBUHandle;
FunctionHandle gSetup_InitialCallForBU_MSHandle;
FunctionHandle gBackup_CallForBUHandle;
FunctionHandle gBackup_UnitBUReplyHandle;
FunctionHandle gBackup_DispBackupReplyHandle;
FunctionHandle gBackup_CallForSwarmingHandle;
FunctionHandle gBackup_DispBUETAHandle;
FunctionHandle gBackup_DispHeliBUETAHandle;
FunctionHandle gBackup_BUReminderHandle;
FunctionHandle gBackup_NegativeBUReplyHandle;
FunctionHandle gBackup_DispBackupUpdateHandle;
FunctionHandle gBackup_BUArrivesHandle;
FunctionHandle gStaticRoadblock_CallForRBHandle;
FunctionHandle gStaticRoadblock_RBReminderHandle;
FunctionHandle gStaticRoadblock_NegativeRBReplyHandle;
FunctionHandle gStaticRoadblock_DispRBReplyHandle;
FunctionHandle gStaticRoadblock_DispRBUpdateHandle;
FunctionHandle gStaticRoadblock_PursuitApproachingHandle;
FunctionHandle gStaticRoadblock_RBApproachHandle;
FunctionHandle gStaticRoadblock_RBEngageHandle;
FunctionHandle gStaticRoadblock_RBAvertedHandle;
FunctionHandle gStaticRoadblock_CallForRB_subHandle;
FunctionHandle gStaticRoadblock_DispSubRBHandle;
FunctionHandle gProjectile_CallForSafetyHandle;
FunctionHandle gProjectile_ProjectileLaunchHandle;
FunctionHandle gProjectile_ProjectileHitHandle;
FunctionHandle gProjectile_ProjectileMissHandle;
FunctionHandle gRollingStrategy_InitStrategyHandle;
FunctionHandle gRollingStrategy_CallToPositionHandle;
FunctionHandle gRollingStrategy_CallToPositionRemHandle;
FunctionHandle gRollingStrategy_StrategyExecuteHandle;
FunctionHandle gOutcome_AnticipateFailHandle;
FunctionHandle gOutcome_AnticipateSuccessHandle;
FunctionHandle gOutcome_OutcomeFailHandle;
FunctionHandle gOutcome_StrategyResetHandle;
FunctionHandle gArrest_BullhornArrestHandle;
FunctionHandle gArrest_ArrestHandle;
FunctionHandle gArrest_DispArrestReplyHandle;
FunctionHandle gAnytimeEvents_CollisionWorldHandle;
FunctionHandle gAnytimeEvents_CollWorld_CiviHandle;
FunctionHandle gAnytimeEvents_CollWorld_SpinHandle;
FunctionHandle gAnytimeEvents_CollWorld_AirHandle;
FunctionHandle gAnytimeEvents_CollWorld_FlipHandle;
FunctionHandle gAnytimeEvents_DispPursuitUpdateHandle;
FunctionHandle gAnytimeEvents_PursuitUpdateRepHandle;
FunctionHandle gAnytimeEvents_Disp911ReportHandle;
FunctionHandle gAnytimeEvents_Disp911CsPntHandle;
FunctionHandle gAnytimeEvents_Disp911NoDescripHandle;
FunctionHandle gAnytimeEvents_Unit911ReplyHandle;
FunctionHandle gAnytimeEvents_SuspectUTurnHandle;
FunctionHandle gAnytimeEvents_SuspectOutrunHandle;
FunctionHandle gAnytimeEvents_LostVisualHandle;
FunctionHandle gAnytimeEvents_RegainVisualHandle;
FunctionHandle gAnytimeEvents_LostSuspectHandle;
FunctionHandle gAnytimeEvents_DispBreakAwayHandle;
FunctionHandle gAnytimeEvents_DispTimeExpiredHandle;
FunctionHandle gAnytimeEvents_DispPursuitEscalationHandle;
FunctionHandle gAnytimeEvents_DispPursEscGenHandle;
FunctionHandle gAnytimeEvents_UnitDisabledHandle;
FunctionHandle gAnytimeEvents_CallForEVHandle;
FunctionHandle gAnytimeEvents_DispEVReplyHandle;
FunctionHandle gAnytimeEvents_IntentToRamHandle;
FunctionHandle gAnytimeEvents_BailoutHandle;
FunctionHandle gAnytimeEvents_BailoutDenyHandle;
FunctionHandle gAnytimeEvents_FocusChangeHandle;
FunctionHandle gAnytimeEvents_SuspectBehaviourHandle;
FunctionHandle gAnytimeEvents_DriverHistoryHandle;
FunctionHandle gAnytimeEvents_OffroadMomentHandle;
FunctionHandle gAnytimeEvents_SpottedHandle;
FunctionHandle gAnytimeEvents_SuspectBrakeHandle;
FunctionHandle gAnytimeEvents_WeatherReportHandle;
FunctionHandle gAnytimeEvents_HeatJumpHandle;
FunctionHandle gAnytimeEvents_DirectionHighHandle;
FunctionHandle gAnytimeEvents_DispJurisShiftHandle;
FunctionHandle gHeliSpecific_HeliSelfStrategyHandle;
FunctionHandle gHeliSpecific_HeliLostVisualHandle;
FunctionHandle gHeliSpecific_HeliIntentToBailHandle;
FunctionHandle gHeliSpecific_HeliBailoutHandle;
FunctionHandle gHeliSpecific_HeliSwarmingHandle;
FunctionHandle gHeliSpecific_HeliSpotterHandle;
FunctionHandle gHeliSpecific_HeliHazardAlertHandle;
FunctionHandle gHeliSpecific_HeliQuadrentHandle;
FunctionHandle gHeliSpecific_HeliQuadrentMovingHandle;
FunctionHandle gHeliSpecific_HeliBullhornArrestHandle;
FunctionHandle gE3_Events_E3_SetupHandle;
FunctionHandle gInterrupts_InterruptHandle;
FunctionHandle gInterrupts_InterruptRamHandle;
FunctionHandle gInterrupts_InterruptRam_REHandle;
FunctionHandle gInterrupts_InterruptRam_HOHandle;
FunctionHandle gInterrupts_InterruptRam_SSHandle;
FunctionHandle gInterrupts_InterruptRam_TBHandle;
FunctionHandle gInterrupts_InterruptRamHighHandle;
FunctionHandle gInterrupts_StaticInterruptHandle;
FunctionHandle gInterrupts_RegainVisualInterruptHandle;
FunctionHandle gCellCallHandle;
FunctionHandle gExtraCops_SwarmingReplyHandle;
FunctionHandle gExtraCops_SuperPursuitReplyHandle;
FunctionHandle gExtraCops_SwarmingReplyFollowHandle;
FunctionHandle gExtraCops_QuadrentFormingHandle;
FunctionHandle gExtraCops_SuspectPossiblyGoneHandle;
FunctionHandle gExtraCops_QuadrentMovingHandle;
FunctionHandle gExtraCops_OtherLeadHandle;
FunctionHandle gExtraCops_PossibleSuspectHandle;
FunctionHandle gExtraCops_WrongSuspectHandle;
FunctionHandle gExtraCops_SuspectGoneHandle;
FunctionHandle gExtraCops_RBWarningHandle;
FunctionHandle gExtraCops_RBPositionHandle;
FunctionHandle gExtraCops_ExtraRBEngageHandle;
FunctionHandle gExtraCops_ExtraRBAvertedHandle;
FunctionHandle gCross_CrossBUReplyHandle;
FunctionHandle gCross_CrossFailReplyHandle;
FunctionHandle gCross_CrossRBFailReplyHandle;
FunctionHandle gCross_CrossPursuitEscHandle;
FunctionHandle gCross_CrossSelfStrategyHandle;
FunctionHandle gCross_CrossMultiStrategyHandle;
FunctionHandle gCross_CrossBailoutDeny_subHandle;
FunctionHandle gD_DayHandle;
FunctionHandle gDispIntroRaceHandle;
FunctionHandle gNIS_Select_StartHandle;
FunctionHandle gNIS_Select_EndHandle;
FunctionHandle gSoundFX_SelectHandle;
FunctionHandle gNIS_Select_BlacklistHandle;

System::Result CacheHandlesEvents() {
    System::Result result = System::kResult_Ok;
    result = static_cast<System::Result>(gAcknowledgeHandle.Set(&AcknowledgeId));
    result = static_cast<System::Result>(gSetup_SpotterHandle.Set(&Setup_SpotterId));
    result = static_cast<System::Result>(gSetup_SpotterWantedHandle.Set(&Setup_SpotterWantedId));
    result = static_cast<System::Result>(gSetup_SpotterReplyHandle.Set(&Setup_SpotterReplyId));
    result = static_cast<System::Result>(gSetup_AttmptVehStpHandle.Set(&Setup_AttmptVehStpId));
    result = static_cast<System::Result>(gSetup_DispGoAheadHandle.Set(&Setup_DispGoAheadId));
    result = static_cast<System::Result>(gSetup_PrimaryEngageHandle.Set(&Setup_PrimaryEngageId));
    result = static_cast<System::Result>(gSetup_InitPursuitHandle.Set(&Setup_InitPursuitId));
    result = static_cast<System::Result>(gSetup_SuspectConfirmedHandle.Set(&Setup_SuspectConfirmedId));
    result = static_cast<System::Result>(gSetup_ReInitPursuitHandle.Set(&Setup_ReInitPursuitId));
    result = static_cast<System::Result>(gSetup_VehicleReportHandle.Set(&Setup_VehicleReportId));
    result = static_cast<System::Result>(gSetup_VehicleReportTagHandle.Set(&Setup_VehicleReportTagId));
    result = static_cast<System::Result>(gSetup_DispVehDescripHandle.Set(&Setup_DispVehDescripId));
    result = static_cast<System::Result>(gSetup_DispVehDescripVinylsHandle.Set(&Setup_DispVehDescripVinylsId));
    result = static_cast<System::Result>(gSetup_DispNoVehDescripHandle.Set(&Setup_DispNoVehDescripId));
    result = static_cast<System::Result>(gSetup_DispCustPaintHandle.Set(&Setup_DispCustPaintId));
    result = static_cast<System::Result>(gSetup_MoreDetailsHandle.Set(&Setup_MoreDetailsId));
    result = static_cast<System::Result>(gSetup_LocationReportHandle.Set(&Setup_LocationReportId));
    result = static_cast<System::Result>(gSetup_BullhornPrefixHandle.Set(&Setup_BullhornPrefixId));
    result = static_cast<System::Result>(gSetup_BullhornHandle.Set(&Setup_BullhornId));
    result = static_cast<System::Result>(gSetup_SelfStrategyHandle.Set(&Setup_SelfStrategyId));
    result = static_cast<System::Result>(gSetup_InitialCallForBUHandle.Set(&Setup_InitialCallForBUId));
    result = static_cast<System::Result>(gSetup_InitialCallForBU_MSHandle.Set(&Setup_InitialCallForBU_MSId));
    result = static_cast<System::Result>(gBackup_CallForBUHandle.Set(&Backup_CallForBUId));
    result = static_cast<System::Result>(gBackup_UnitBUReplyHandle.Set(&Backup_UnitBUReplyId));
    result = static_cast<System::Result>(gBackup_DispBackupReplyHandle.Set(&Backup_DispBackupReplyId));
    result = static_cast<System::Result>(gBackup_CallForSwarmingHandle.Set(&Backup_CallForSwarmingId));
    result = static_cast<System::Result>(gBackup_DispBUETAHandle.Set(&Backup_DispBUETAId));
    result = static_cast<System::Result>(gBackup_DispHeliBUETAHandle.Set(&Backup_DispHeliBUETAId));
    result = static_cast<System::Result>(gBackup_BUReminderHandle.Set(&Backup_BUReminderId));
    result = static_cast<System::Result>(gBackup_NegativeBUReplyHandle.Set(&Backup_NegativeBUReplyId));
    result = static_cast<System::Result>(gBackup_DispBackupUpdateHandle.Set(&Backup_DispBackupUpdateId));
    result = static_cast<System::Result>(gBackup_BUArrivesHandle.Set(&Backup_BUArrivesId));
    result = static_cast<System::Result>(gStaticRoadblock_CallForRBHandle.Set(&StaticRoadblock_CallForRBId));
    result = static_cast<System::Result>(gStaticRoadblock_RBReminderHandle.Set(&StaticRoadblock_RBReminderId));
    result = static_cast<System::Result>(gStaticRoadblock_NegativeRBReplyHandle.Set(&StaticRoadblock_NegativeRBReplyId));
    result = static_cast<System::Result>(gStaticRoadblock_DispRBReplyHandle.Set(&StaticRoadblock_DispRBReplyId));
    result = static_cast<System::Result>(gStaticRoadblock_DispRBUpdateHandle.Set(&StaticRoadblock_DispRBUpdateId));
    result = static_cast<System::Result>(gStaticRoadblock_PursuitApproachingHandle.Set(&StaticRoadblock_PursuitApproachingId));
    result = static_cast<System::Result>(gStaticRoadblock_RBApproachHandle.Set(&StaticRoadblock_RBApproachId));
    result = static_cast<System::Result>(gStaticRoadblock_RBEngageHandle.Set(&StaticRoadblock_RBEngageId));
    result = static_cast<System::Result>(gStaticRoadblock_RBAvertedHandle.Set(&StaticRoadblock_RBAvertedId));
    result = static_cast<System::Result>(gStaticRoadblock_CallForRB_subHandle.Set(&StaticRoadblock_CallForRB_subId));
    result = static_cast<System::Result>(gStaticRoadblock_DispSubRBHandle.Set(&StaticRoadblock_DispSubRBId));
    result = static_cast<System::Result>(gProjectile_CallForSafetyHandle.Set(&Projectile_CallForSafetyId));
    result = static_cast<System::Result>(gProjectile_ProjectileLaunchHandle.Set(&Projectile_ProjectileLaunchId));
    result = static_cast<System::Result>(gProjectile_ProjectileHitHandle.Set(&Projectile_ProjectileHitId));
    result = static_cast<System::Result>(gProjectile_ProjectileMissHandle.Set(&Projectile_ProjectileMissId));
    result = static_cast<System::Result>(gRollingStrategy_InitStrategyHandle.Set(&RollingStrategy_InitStrategyId));
    result = static_cast<System::Result>(gRollingStrategy_CallToPositionHandle.Set(&RollingStrategy_CallToPositionId));
    result = static_cast<System::Result>(gRollingStrategy_CallToPositionRemHandle.Set(&RollingStrategy_CallToPositionRemId));
    result = static_cast<System::Result>(gRollingStrategy_StrategyExecuteHandle.Set(&RollingStrategy_StrategyExecuteId));
    result = static_cast<System::Result>(gOutcome_AnticipateFailHandle.Set(&Outcome_AnticipateFailId));
    result = static_cast<System::Result>(gOutcome_AnticipateSuccessHandle.Set(&Outcome_AnticipateSuccessId));
    result = static_cast<System::Result>(gOutcome_OutcomeFailHandle.Set(&Outcome_OutcomeFailId));
    result = static_cast<System::Result>(gOutcome_StrategyResetHandle.Set(&Outcome_StrategyResetId));
    result = static_cast<System::Result>(gArrest_BullhornArrestHandle.Set(&Arrest_BullhornArrestId));
    result = static_cast<System::Result>(gArrest_ArrestHandle.Set(&Arrest_ArrestId));
    result = static_cast<System::Result>(gArrest_DispArrestReplyHandle.Set(&Arrest_DispArrestReplyId));
    result = static_cast<System::Result>(gAnytimeEvents_CollisionWorldHandle.Set(&AnytimeEvents_CollisionWorldId));
    result = static_cast<System::Result>(gAnytimeEvents_CollWorld_CiviHandle.Set(&AnytimeEvents_CollWorld_CiviId));
    result = static_cast<System::Result>(gAnytimeEvents_CollWorld_SpinHandle.Set(&AnytimeEvents_CollWorld_SpinId));
    result = static_cast<System::Result>(gAnytimeEvents_CollWorld_AirHandle.Set(&AnytimeEvents_CollWorld_AirId));
    result = static_cast<System::Result>(gAnytimeEvents_CollWorld_FlipHandle.Set(&AnytimeEvents_CollWorld_FlipId));
    result = static_cast<System::Result>(gAnytimeEvents_DispPursuitUpdateHandle.Set(&AnytimeEvents_DispPursuitUpdateId));
    result = static_cast<System::Result>(gAnytimeEvents_PursuitUpdateRepHandle.Set(&AnytimeEvents_PursuitUpdateRepId));
    result = static_cast<System::Result>(gAnytimeEvents_Disp911ReportHandle.Set(&AnytimeEvents_Disp911ReportId));
    result = static_cast<System::Result>(gAnytimeEvents_Disp911CsPntHandle.Set(&AnytimeEvents_Disp911CsPntId));
    result = static_cast<System::Result>(gAnytimeEvents_Disp911NoDescripHandle.Set(&AnytimeEvents_Disp911NoDescripId));
    result = static_cast<System::Result>(gAnytimeEvents_Unit911ReplyHandle.Set(&AnytimeEvents_Unit911ReplyId));
    result = static_cast<System::Result>(gAnytimeEvents_SuspectUTurnHandle.Set(&AnytimeEvents_SuspectUTurnId));
    result = static_cast<System::Result>(gAnytimeEvents_SuspectOutrunHandle.Set(&AnytimeEvents_SuspectOutrunId));
    result = static_cast<System::Result>(gAnytimeEvents_LostVisualHandle.Set(&AnytimeEvents_LostVisualId));
    result = static_cast<System::Result>(gAnytimeEvents_RegainVisualHandle.Set(&AnytimeEvents_RegainVisualId));
    result = static_cast<System::Result>(gAnytimeEvents_LostSuspectHandle.Set(&AnytimeEvents_LostSuspectId));
    result = static_cast<System::Result>(gAnytimeEvents_DispBreakAwayHandle.Set(&AnytimeEvents_DispBreakAwayId));
    result = static_cast<System::Result>(gAnytimeEvents_DispTimeExpiredHandle.Set(&AnytimeEvents_DispTimeExpiredId));
    result = static_cast<System::Result>(gAnytimeEvents_DispPursuitEscalationHandle.Set(&AnytimeEvents_DispPursuitEscalationId));
    result = static_cast<System::Result>(gAnytimeEvents_DispPursEscGenHandle.Set(&AnytimeEvents_DispPursEscGenId));
    result = static_cast<System::Result>(gAnytimeEvents_UnitDisabledHandle.Set(&AnytimeEvents_UnitDisabledId));
    result = static_cast<System::Result>(gAnytimeEvents_CallForEVHandle.Set(&AnytimeEvents_CallForEVId));
    result = static_cast<System::Result>(gAnytimeEvents_DispEVReplyHandle.Set(&AnytimeEvents_DispEVReplyId));
    result = static_cast<System::Result>(gAnytimeEvents_IntentToRamHandle.Set(&AnytimeEvents_IntentToRamId));
    result = static_cast<System::Result>(gAnytimeEvents_BailoutHandle.Set(&AnytimeEvents_BailoutId));
    result = static_cast<System::Result>(gAnytimeEvents_BailoutDenyHandle.Set(&AnytimeEvents_BailoutDenyId));
    result = static_cast<System::Result>(gAnytimeEvents_FocusChangeHandle.Set(&AnytimeEvents_FocusChangeId));
    result = static_cast<System::Result>(gAnytimeEvents_SuspectBehaviourHandle.Set(&AnytimeEvents_SuspectBehaviourId));
    result = static_cast<System::Result>(gAnytimeEvents_DriverHistoryHandle.Set(&AnytimeEvents_DriverHistoryId));
    result = static_cast<System::Result>(gAnytimeEvents_OffroadMomentHandle.Set(&AnytimeEvents_OffroadMomentId));
    result = static_cast<System::Result>(gAnytimeEvents_SpottedHandle.Set(&AnytimeEvents_SpottedId));
    result = static_cast<System::Result>(gAnytimeEvents_SuspectBrakeHandle.Set(&AnytimeEvents_SuspectBrakeId));
    result = static_cast<System::Result>(gAnytimeEvents_WeatherReportHandle.Set(&AnytimeEvents_WeatherReportId));
    result = static_cast<System::Result>(gAnytimeEvents_HeatJumpHandle.Set(&AnytimeEvents_HeatJumpId));
    result = static_cast<System::Result>(gAnytimeEvents_DirectionHighHandle.Set(&AnytimeEvents_DirectionHighId));
    result = static_cast<System::Result>(gAnytimeEvents_DispJurisShiftHandle.Set(&AnytimeEvents_DispJurisShiftId));
    result = static_cast<System::Result>(gHeliSpecific_HeliSelfStrategyHandle.Set(&HeliSpecific_HeliSelfStrategyId));
    result = static_cast<System::Result>(gHeliSpecific_HeliLostVisualHandle.Set(&HeliSpecific_HeliLostVisualId));
    result = static_cast<System::Result>(gHeliSpecific_HeliIntentToBailHandle.Set(&HeliSpecific_HeliIntentToBailId));
    result = static_cast<System::Result>(gHeliSpecific_HeliBailoutHandle.Set(&HeliSpecific_HeliBailoutId));
    result = static_cast<System::Result>(gHeliSpecific_HeliSwarmingHandle.Set(&HeliSpecific_HeliSwarmingId));
    result = static_cast<System::Result>(gHeliSpecific_HeliSpotterHandle.Set(&HeliSpecific_HeliSpotterId));
    result = static_cast<System::Result>(gHeliSpecific_HeliHazardAlertHandle.Set(&HeliSpecific_HeliHazardAlertId));
    result = static_cast<System::Result>(gHeliSpecific_HeliQuadrentHandle.Set(&HeliSpecific_HeliQuadrentId));
    result = static_cast<System::Result>(gHeliSpecific_HeliQuadrentMovingHandle.Set(&HeliSpecific_HeliQuadrentMovingId));
    result = static_cast<System::Result>(gHeliSpecific_HeliBullhornArrestHandle.Set(&HeliSpecific_HeliBullhornArrestId));
    result = static_cast<System::Result>(gE3_Events_E3_SetupHandle.Set(&E3_Events_E3_SetupId));
    result = static_cast<System::Result>(gInterrupts_InterruptHandle.Set(&Interrupts_InterruptId));
    result = static_cast<System::Result>(gInterrupts_InterruptRamHandle.Set(&Interrupts_InterruptRamId));
    result = static_cast<System::Result>(gInterrupts_InterruptRam_REHandle.Set(&Interrupts_InterruptRam_REId));
    result = static_cast<System::Result>(gInterrupts_InterruptRam_HOHandle.Set(&Interrupts_InterruptRam_HOId));
    result = static_cast<System::Result>(gInterrupts_InterruptRam_SSHandle.Set(&Interrupts_InterruptRam_SSId));
    result = static_cast<System::Result>(gInterrupts_InterruptRam_TBHandle.Set(&Interrupts_InterruptRam_TBId));
    result = static_cast<System::Result>(gInterrupts_InterruptRamHighHandle.Set(&Interrupts_InterruptRamHighId));
    result = static_cast<System::Result>(gInterrupts_StaticInterruptHandle.Set(&Interrupts_StaticInterruptId));
    result = static_cast<System::Result>(gInterrupts_RegainVisualInterruptHandle.Set(&Interrupts_RegainVisualInterruptId));
    result = static_cast<System::Result>(gCellCallHandle.Set(&CellCallId));
    result = static_cast<System::Result>(gExtraCops_SwarmingReplyHandle.Set(&ExtraCops_SwarmingReplyId));
    result = static_cast<System::Result>(gExtraCops_SuperPursuitReplyHandle.Set(&ExtraCops_SuperPursuitReplyId));
    result = static_cast<System::Result>(gExtraCops_SwarmingReplyFollowHandle.Set(&ExtraCops_SwarmingReplyFollowId));
    result = static_cast<System::Result>(gExtraCops_QuadrentFormingHandle.Set(&ExtraCops_QuadrentFormingId));
    result = static_cast<System::Result>(gExtraCops_SuspectPossiblyGoneHandle.Set(&ExtraCops_SuspectPossiblyGoneId));
    result = static_cast<System::Result>(gExtraCops_QuadrentMovingHandle.Set(&ExtraCops_QuadrentMovingId));
    result = static_cast<System::Result>(gExtraCops_OtherLeadHandle.Set(&ExtraCops_OtherLeadId));
    result = static_cast<System::Result>(gExtraCops_PossibleSuspectHandle.Set(&ExtraCops_PossibleSuspectId));
    result = static_cast<System::Result>(gExtraCops_WrongSuspectHandle.Set(&ExtraCops_WrongSuspectId));
    result = static_cast<System::Result>(gExtraCops_SuspectGoneHandle.Set(&ExtraCops_SuspectGoneId));
    result = static_cast<System::Result>(gExtraCops_RBWarningHandle.Set(&ExtraCops_RBWarningId));
    result = static_cast<System::Result>(gExtraCops_RBPositionHandle.Set(&ExtraCops_RBPositionId));
    result = static_cast<System::Result>(gExtraCops_ExtraRBEngageHandle.Set(&ExtraCops_ExtraRBEngageId));
    result = static_cast<System::Result>(gExtraCops_ExtraRBAvertedHandle.Set(&ExtraCops_ExtraRBAvertedId));
    result = static_cast<System::Result>(gCross_CrossBUReplyHandle.Set(&Cross_CrossBUReplyId));
    result = static_cast<System::Result>(gCross_CrossFailReplyHandle.Set(&Cross_CrossFailReplyId));
    result = static_cast<System::Result>(gCross_CrossRBFailReplyHandle.Set(&Cross_CrossRBFailReplyId));
    result = static_cast<System::Result>(gCross_CrossPursuitEscHandle.Set(&Cross_CrossPursuitEscId));
    result = static_cast<System::Result>(gCross_CrossSelfStrategyHandle.Set(&Cross_CrossSelfStrategyId));
    result = static_cast<System::Result>(gCross_CrossMultiStrategyHandle.Set(&Cross_CrossMultiStrategyId));
    result = static_cast<System::Result>(gCross_CrossBailoutDeny_subHandle.Set(&Cross_CrossBailoutDeny_subId));
    result = static_cast<System::Result>(gD_DayHandle.Set(&D_DayId));
    result = static_cast<System::Result>(gDispIntroRaceHandle.Set(&DispIntroRaceId));
    return result;
}

System::Result CacheHandlesEventsNIS() {
    System::Result result = System::kResult_Ok;
    result = static_cast<System::Result>(gNIS_Select_StartHandle.Set(&NIS_Select_StartId));
    result = static_cast<System::Result>(gNIS_Select_EndHandle.Set(&NIS_Select_EndId));
    result = static_cast<System::Result>(gSoundFX_SelectHandle.Set(&SoundFX_SelectId));
    result = static_cast<System::Result>(gNIS_Select_BlacklistHandle.Set(&NIS_Select_BlacklistId));
    return result;
}
} // namespace Csis
