#include "Speed/Indep/Src/World/CarInfo.hpp"
#include "string.h"

CarPartIDNameMap CarPartIDNames[CARPARTID_NUM] = {
    {CARPARTID_BASE, "BASE", UCrc32("BASE")},
    {CARPARTID_DAMAGE_FRONT_WINDOW, "DAMAGE_FRONT_WINDOW", UCrc32("DAMAGE_FRONT_WINDOW")},
    {CARPARTID_DAMAGE_BODY, "DAMAGE_BODY", UCrc32("DAMAGE_BODY")},
    {CARPARTID_DAMAGE_COP_LIGHTS, "DAMAGE_COP_LIGHTS", UCrc32("DAMAGE_COP_LIGHTS")},
    {CARPARTID_DAMAGE_COP_SPOILER, "DAMAGE_COP_SPOILER", UCrc32("DAMAGE_COP_SPOILER")},
    {CARPARTID_DAMAGE_FRONT_WHEEL, "DAMAGE_FRONT_WHEEL", UCrc32("DAMAGE_FRONT_WHEEL")},
    {CARPARTID_DAMAGE_LEFT_BRAKELIGHT, "DAMAGE_LEFT_BRAKELIGHT", UCrc32("DAMAGE_LEFT_BRAKELIGHT")},
    {CARPARTID_DAMAGE_RIGHT_BRAKELIGHT, "DAMAGE_RIGHT_BRAKELIGHT", UCrc32("DAMAGE_RIGHT_BRAKELIGHT")},
    {CARPARTID_DAMAGE_LEFT_HEADLIGHT, "DAMAGE_LEFT_HEADLIGHT", UCrc32("DAMAGE_LEFT_HEADLIGHT")},
    {CARPARTID_DAMAGE_RIGHT_HEADLIGHT, "DAMAGE_RIGHT_HEADLIGHT", UCrc32("DAMAGE_RIGHT_HEADLIGHT")},
    {CARPARTID_DAMAGE_HOOD, "DAMAGE_HOOD", UCrc32("DAMAGE_HOOD")},
    {CARPARTID_DAMAGE_BUSHGUARD, "DAMAGE_BUSHGUARD", UCrc32("DAMAGE_BUSHGUARD")},
    {CARPARTID_DAMAGE_FRONT_BUMPER, "DAMAGE_FRONT_BUMPER", UCrc32("DAMAGE_FRONT_BUMPER")},
    {CARPARTID_DAMAGE_RIGHT_DOOR, "DAMAGE_RIGHT_DOOR", UCrc32("DAMAGE_RIGHT_DOOR")},
    {CARPARTID_DAMAGE_RIGHT_REAR_DOOR, "DAMAGE_RIGHT_REAR_DOOR", UCrc32("DAMAGE_RIGHT_REAR_DOOR")},
    {CARPARTID_DAMAGE_TRUNK, "DAMAGE_TRUNK", UCrc32("DAMAGE_TRUNK")},
    {CARPARTID_DAMAGE_REAR_BUMPER, "DAMAGE_REAR_BUMPER", UCrc32("DAMAGE_REAR_BUMPER")},
    {CARPARTID_DAMAGE_REAR_LEFT_WINDOW, "DAMAGE_REAR_LEFT_WINDOW", UCrc32("DAMAGE_REAR_LEFT_WINDOW")},
    {CARPARTID_DAMAGE_FRONT_LEFT_WINDOW, "DAMAGE_FRONT_LEFT_WINDOW", UCrc32("DAMAGE_FRONT_LEFT_WINDOW")},
    {CARPARTID_DAMAGE_FRONT_RIGHT_WINDOW, "DAMAGE_FRONT_RIGHT_WINDOW", UCrc32("DAMAGE_FRONT_RIGHT_WINDOW")},
    {CARPARTID_DAMAGE_REAR_RIGHT_WINDOW, "DAMAGE_REAR_RIGHT_WINDOW", UCrc32("DAMAGE_REAR_RIGHT_WINDOW")},
    {CARPARTID_DAMAGE_LEFT_DOOR, "DAMAGE_LEFT_DOOR", UCrc32("DAMAGE_LEFT_DOOR")},
    {CARPARTID_DAMAGE_LEFT_REAR_DOOR, "DAMAGE_LEFT_REAR_DOOR", UCrc32("DAMAGE_LEFT_REAR_DOOR")},
    {CARPARTID_BODY, "BODY", UCrc32("BODY")},
    {CARPARTID_FRONT_BRAKE, "FRONT_BRAKE", UCrc32("FRONT_BRAKE")},
    {CARPARTID_FRONT_LEFT_WINDOW, "FRONT_LEFT_WINDOW", UCrc32("FRONT_LEFT_WINDOW")},
    {CARPARTID_FRONT_RIGHT_WINDOW, "FRONT_RIGHT_WINDOW", UCrc32("FRONT_RIGHT_WINDOW")},
    {CARPARTID_FRONT_WINDOW, "FRONT_WINDOW", UCrc32("FRONT_WINDOW")},
    {CARPARTID_INTERIOR, "INTERIOR", UCrc32("INTERIOR")},
    {CARPARTID_LEFT_BRAKELIGHT, "LEFT_BRAKELIGHT", UCrc32("LEFT_BRAKELIGHT")},
    {CARPARTID_LEFT_BRAKELIGHT_GLASS, "LEFT_BRAKELIGHT_GLASS", UCrc32("LEFT_BRAKELIGHT_GLASS")},
    {CARPARTID_LEFT_HEADLIGHT, "LEFT_HEADLIGHT", UCrc32("LEFT_HEADLIGHT")},
    {CARPARTID_LEFT_HEADLIGHT_GLASS, "LEFT_HEADLIGHT_GLASS", UCrc32("LEFT_HEADLIGHT_GLASS")},
    {CARPARTID_LEFT_SIDE_MIRROR, "LEFT_SIDE_MIRROR", UCrc32("LEFT_SIDE_MIRROR")},
    {CARPARTID_REAR_BRAKE, "REAR_BRAKE", UCrc32("REAR_BRAKE")},
    {CARPARTID_REAR_LEFT_WINDOW, "REAR_LEFT_WINDOW", UCrc32("REAR_LEFT_WINDOW")},
    {CARPARTID_REAR_RIGHT_WINDOW, "REAR_RIGHT_WINDOW", UCrc32("REAR_RIGHT_WINDOW")},
    {CARPARTID_REAR_WINDOW, "REAR_WINDOW", UCrc32("REAR_WINDOW")},
    {CARPARTID_RIGHT_BRAKELIGHT, "RIGHT_BRAKELIGHT", UCrc32("RIGHT_BRAKELIGHT")},
    {CARPARTID_RIGHT_BRAKELIGHT_GLASS, "RIGHT_BRAKELIGHT_GLASS", UCrc32("RIGHT_BRAKELIGHT_GLASS")},
    {CARPARTID_RIGHT_HEADLIGHT, "RIGHT_HEADLIGHT", UCrc32("RIGHT_HEADLIGHT")},
    {CARPARTID_RIGHT_HEADLIGHT_GLASS, "RIGHT_HEADLIGHT_GLASS", UCrc32("RIGHT_HEADLIGHT_GLASS")},
    {CARPARTID_RIGHT_SIDE_MIRROR, "RIGHT_SIDE_MIRROR", UCrc32("RIGHT_SIDE_MIRROR")},
    {CARPARTID_DRIVER, "DRIVER", UCrc32("DRIVER")},
    {CARPARTID_SPOILER, "SPOILER", UCrc32("SPOILER")},
    {CARPARTID_UNIVERSAL_SPOILER_BASE, "UNIVERSAL_SPOILER_BASE", UCrc32("UNIVERSAL_SPOILER_BASE")},
    {CARPARTID_DAMAGE0_FRONT, "DAMAGE0_FRONT", UCrc32("DAMAGE0_FRONT")},
    {CARPARTID_DAMAGE0_FRONTLEFT, "DAMAGE0_FRONTLEFT", UCrc32("DAMAGE0_FRONTLEFT")},
    {CARPARTID_DAMAGE0_FRONTRIGHT, "DAMAGE0_FRONTRIGHT", UCrc32("DAMAGE0_FRONTRIGHT")},
    {CARPARTID_DAMAGE0_REAR, "DAMAGE0_REAR", UCrc32("DAMAGE0_REAR")},
    {CARPARTID_DAMAGE0_REARLEFT, "DAMAGE0_REARLEFT", UCrc32("DAMAGE0_REARLEFT")},
    {CARPARTID_DAMAGE0_REARRIGHT, "DAMAGE0_REARRIGHT", UCrc32("DAMAGE0_REARRIGHT")},
    {CARPARTID_ATTACHMENT0, "ATTACHMENT0", UCrc32("ATTACHMENT0")},
    {CARPARTID_ATTACHMENT1, "ATTACHMENT1", UCrc32("ATTACHMENT1")},
    {CARPARTID_ATTACHMENT2, "ATTACHMENT2", UCrc32("ATTACHMENT2")},
    {CARPARTID_ATTACHMENT3, "ATTACHMENT3", UCrc32("ATTACHMENT3")},
    {CARPARTID_ATTACHMENT4, "ATTACHMENT4", UCrc32("ATTACHMENT4")},
    {CARPARTID_ATTACHMENT5, "ATTACHMENT5", UCrc32("ATTACHMENT5")},
    {CARPARTID_ATTACHMENT6, "ATTACHMENT6", UCrc32("ATTACHMENT6")},
    {CARPARTID_ATTACHMENT7, "ATTACHMENT7", UCrc32("ATTACHMENT7")},
    {CARPARTID_ATTACHMENT8, "ATTACHMENT8", UCrc32("ATTACHMENT8")},
    {CARPARTID_ATTACHMENT9, "ATTACHMENT9", UCrc32("ATTACHMENT9")},
    {CARPARTID_ROOF, "ROOF", UCrc32("ROOF")},
    {CARPARTID_HOOD, "HOOD", UCrc32("HOOD")},
    {CARPARTID_HEADLIGHT, "HEADLIGHT", UCrc32("HEADLIGHT")},
    {CARPARTID_BRAKELIGHT, "BRAKELIGHT", UCrc32("BRAKELIGHT")},
    {CARPARTID_BRAKE, "BRAKE", UCrc32("BRAKE")},
    {CARPARTID_WHEEL, "WHEEL", UCrc32("WHEEL")},
    {CARPARTID_SPINNER, "SPINNER", UCrc32("SPINNER")},
    {CARPARTID_LICENSE_PLATE, "LICENSE_PLATE", UCrc32("LICENSE_PLATE")},
    {CARPARTID_DECAL_FRONT_WINDOW, "DECAL_FRONT_WINDOW", UCrc32("DECAL_FRONT_WINDOW")},
    {CARPARTID_DECAL_REAR_WINDOW, "DECAL_REAR_WINDOW", UCrc32("DECAL_REAR_WINDOW")},
    {CARPARTID_DECAL_LEFT_DOOR, "DECAL_LEFT_DOOR", UCrc32("DECAL_LEFT_DOOR")},
    {CARPARTID_DECAL_RIGHT_DOOR, "DECAL_RIGHT_DOOR", UCrc32("DECAL_RIGHT_DOOR")},
    {CARPARTID_DECAL_LEFT_QUARTER, "DECAL_LEFT_QUARTER", UCrc32("DECAL_LEFT_QUARTER")},
    {CARPARTID_DECAL_RIGHT_QUARTER, "DECAL_RIGHT_QUARTER", UCrc32("DECAL_RIGHT_QUARTER")},
    {CARPARTID_PAINT, "PAINT", UCrc32("PAINT")},
    {CARPARTID_VINYL_PAINT, "VINYL_PAINT", UCrc32("VINYL_PAINT")},
    {CARPARTID_RIM_PAINT, "RIM_PAINT", UCrc32("RIM_PAINT")},
    {CARPARTID_VINYL, "VINYL", UCrc32("VINYL")},
    {CARPARTID_DECAL_TEXTURE, "DECAL_TEXTURE", UCrc32("DECAL_TEXTURE")},
    {CARPARTID_WINDOW_TINT, "WINDOW_TINT", UCrc32("WINDOW_TINT")},
    {CARPARTID_CUSTOM_HUD, "CUSTOM_HUD", UCrc32("CUSTOM_HUD")},
    {CARPARTID_CUSTOM_HUD_PAINT, "CUSTOM_HUD_PAINT", UCrc32("CUSTOM_HUD_PAINT")},
    {CARPARTID_CV, "CV", UCrc32("CV")},
    {CARPARTID_WHEEL_MANUFACTURER, "WHEEL_MANUFACTURER", UCrc32("WHEEL_MANUFACTURER")},
    {CARPARTID_MISC, "MISC", UCrc32("MISC")},
};
CarPartIDNameMap CarPartIDOldNames[1] = {CARPARTID_BRAKE, "BRAKE", UCrc32("BRAKE")};
CarSlotIDNameMap CarSlotIDNames[CARSLOTID_NUM] = {
    {CARSLOTID_BASE, "BASE"},
    {CARSLOTID_DAMAGE_FRONT_WINDOW, "DAMAGE_FRONT_WINDOW"},
    {CARSLOTID_DAMAGE_BODY, "DAMAGE_BODY"},
    {CARSLOTID_DAMAGE_COP_LIGHTS, "DAMAGE_COP_LIGHTS"},
    {CARSLOTID_DAMAGE_COP_SPOILER, "DAMAGE_COP_SPOILER"},
    {CARSLOTID_DAMAGE_FRONT_WHEEL, "DAMAGE_FRONT_WHEEL"},
    {CARSLOTID_DAMAGE_LEFT_BRAKELIGHT, "DAMAGE_LEFT_BRAKELIGHT"},
    {CARSLOTID_DAMAGE_RIGHT_BRAKELIGHT, "DAMAGE_RIGHT_BRAKELIGHT"},
    {CARSLOTID_DAMAGE_LEFT_HEADLIGHT, "DAMAGE_LEFT_HEADLIGHT"},
    {CARSLOTID_DAMAGE_RIGHT_HEADLIGHT, "DAMAGE_RIGHT_HEADLIGHT"},
    {CARSLOTID_DAMAGE_HOOD, "DAMAGE_HOOD"},
    {CARSLOTID_DAMAGE_BUSHGUARD, "DAMAGE_BUSHGUARD"},
    {CARSLOTID_DAMAGE_FRONT_BUMPER, "DAMAGE_FRONT_BUMPER"},
    {CARSLOTID_DAMAGE_RIGHT_DOOR, "DAMAGE_RIGHT_DOOR"},
    {CARSLOTID_DAMAGE_RIGHT_REAR_DOOR, "DAMAGE_RIGHT_REAR_DOOR"},
    {CARSLOTID_DAMAGE_TRUNK, "DAMAGE_TRUNK"},
    {CARSLOTID_DAMAGE_REAR_BUMPER, "DAMAGE_REAR_BUMPER"},
    {CARSLOTID_DAMAGE_REAR_LEFT_WINDOW, "DAMAGE_REAR_LEFT_WINDOW"},
    {CARSLOTID_DAMAGE_FRONT_LEFT_WINDOW, "DAMAGE_FRONT_LEFT_WINDOW"},
    {CARSLOTID_DAMAGE_FRONT_RIGHT_WINDOW, "DAMAGE_FRONT_RIGHT_WINDOW"},
    {CARSLOTID_DAMAGE_REAR_RIGHT_WINDOW, "DAMAGE_REAR_RIGHT_WINDOW"},
    {CARSLOTID_DAMAGE_LEFT_DOOR, "DAMAGE_LEFT_DOOR"},
    {CARSLOTID_DAMAGE_LEFT_REAR_DOOR, "DAMAGE_LEFT_REAR_DOOR"},
    {CARSLOTID_BODY, "BODY"},
    {CARSLOTID_FRONT_BRAKE, "FRONT_BRAKE"},
    {CARSLOTID_FRONT_LEFT_WINDOW, "FRONT_LEFT_WINDOW"},
    {CARSLOTID_FRONT_RIGHT_WINDOW, "FRONT_RIGHT_WINDOW"},
    {CARSLOTID_FRONT_WINDOW, "FRONT_WINDOW"},
    {CARSLOTID_INTERIOR, "INTERIOR"},
    {CARSLOTID_LEFT_BRAKELIGHT, "LEFT_BRAKELIGHT"},
    {CARSLOTID_LEFT_BRAKELIGHT_GLASS, "LEFT_BRAKELIGHT_GLASS"},
    {CARSLOTID_LEFT_HEADLIGHT, "LEFT_HEADLIGHT"},
    {CARSLOTID_LEFT_HEADLIGHT_GLASS, "LEFT_HEADLIGHT_GLASS"},
    {CARSLOTID_LEFT_SIDE_MIRROR, "LEFT_SIDE_MIRROR"},
    {CARSLOTID_REAR_BRAKE, "REAR_BRAKE"},
    {CARSLOTID_REAR_LEFT_WINDOW, "REAR_LEFT_WINDOW"},
    {CARSLOTID_REAR_RIGHT_WINDOW, "REAR_RIGHT_WINDOW"},
    {CARSLOTID_REAR_WINDOW, "REAR_WINDOW"},
    {CARSLOTID_RIGHT_BRAKELIGHT, "RIGHT_BRAKELIGHT"},
    {CARSLOTID_RIGHT_BRAKELIGHT_GLASS, "RIGHT_BRAKELIGHT_GLASS"},
    {CARSLOTID_RIGHT_HEADLIGHT, "RIGHT_HEADLIGHT"},
    {CARSLOTID_RIGHT_HEADLIGHT_GLASS, "RIGHT_HEADLIGHT_GLASS"},
    {CARSLOTID_RIGHT_SIDE_MIRROR, "RIGHT_SIDE_MIRROR"},
    {CARSLOTID_DRIVER, "DRIVER"},
    {CARSLOTID_SPOILER, "SPOILER"},
    {CARSLOTID_UNIVERSAL_SPOILER_BASE, "UNIVERSAL_SPOILER_BASE"},
    {CARSLOTID_DAMAGE0_FRONT, "DAMAGE0_FRONT"},
    {CARSLOTID_DAMAGE0_FRONTLEFT, "DAMAGE0_FRONTLEFT"},
    {CARSLOTID_DAMAGE0_FRONTRIGHT, "DAMAGE0_FRONTRIGHT"},
    {CARSLOTID_DAMAGE0_REAR, "DAMAGE0_REAR"},
    {CARSLOTID_DAMAGE0_REARLEFT, "DAMAGE0_REARLEFT"},
    {CARSLOTID_DAMAGE0_REARRIGHT, "DAMAGE0_REARRIGHT"},
    {CARSLOTID_ATTACHMENT0, "ATTACHMENT0"},
    {CARSLOTID_ATTACHMENT1, "ATTACHMENT1"},
    {CARSLOTID_ATTACHMENT2, "ATTACHMENT2"},
    {CARSLOTID_ATTACHMENT3, "ATTACHMENT3"},
    {CARSLOTID_ATTACHMENT4, "ATTACHMENT4"},
    {CARSLOTID_ATTACHMENT5, "ATTACHMENT5"},
    {CARSLOTID_ATTACHMENT6, "ATTACHMENT6"},
    {CARSLOTID_ATTACHMENT7, "ATTACHMENT7"},
    {CARSLOTID_ATTACHMENT8, "ATTACHMENT8"},
    {CARSLOTID_ATTACHMENT9, "ATTACHMENT9"},
    {CARSLOTID_ROOF, "ROOF"},
    {CARSLOTID_HOOD, "HOOD"},
    {CARSLOTID_HEADLIGHT, "HEADLIGHT"},
    {CARSLOTID_BRAKELIGHT, "BRAKELIGHT"},
    {CARSLOTID_FRONT_WHEEL, "FRONT_WHEEL"},
    {CARSLOTID_REAR_WHEEL, "REAR_WHEEL"},
    {CARSLOTID_SPINNER, "SPINNER"},
    {CARSLOTID_LICENSE_PLATE, "LICENSE_PLATE"},
    {CARSLOTID_DECAL_FRONT_WINDOW, "DECAL_FRONT_WINDOW_WIDE_MEDIUM"},
    {CARSLOTID_DECAL_REAR_WINDOW, "DECAL_REAR_WINDOW_WIDE_MEDIUM"},
    {CARSLOTID_DECAL_LEFT_DOOR, "DECAL_LEFT_DOOR_RECT_MEDIUM"},
    {CARSLOTID_DECAL_RIGHT_DOOR, "DECAL_RIGHT_DOOR_RECT_MEDIUM"},
    {CARSLOTID_DECAL_LEFT_QUARTER, "DECAL_LEFT_QUARTER_RECT_MEDIUM"},
    {CARSLOTID_DECAL_RIGHT_QUARTER, "DECAL_RIGHT_QUARTER_RECT_MEDIUM"},
    {CARSLOTID_BASE_PAINT, "BASE_PAINT"},
    {CARSLOTID_VINYL_LAYER0, "VINYL_LAYER0"},
    {CARSLOTID_PAINT_RIM, "PAINT_RIM"},
    {CARSLOTID_VINYL_COLOUR0_0, "VINYL_COLOUR0_0"},
    {CARSLOTID_VINYL_COLOUR0_1, "VINYL_COLOUR0_1"},
    {CARSLOTID_VINYL_COLOUR0_2, "VINYL_COLOUR0_2"},
    {CARSLOTID_VINYL_COLOUR0_3, "VINYL_COLOUR0_3"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX0, "DECAL_FRONT_WINDOW_TEX0"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX1, "DECAL_FRONT_WINDOW_TEX1"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX2, "DECAL_FRONT_WINDOW_TEX2"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX3, "DECAL_FRONT_WINDOW_TEX3"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX4, "DECAL_FRONT_WINDOW_TEX4"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX5, "DECAL_FRONT_WINDOW_TEX5"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX6, "DECAL_FRONT_WINDOW_TEX6"},
    {CARSLOTID_DECAL_FRONT_WINDOW_TEX7, "DECAL_FRONT_WINDOW_TEX7"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX0, "DECAL_REAR_WINDOW_TEX0"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX1, "DECAL_REAR_WINDOW_TEX1"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX2, "DECAL_REAR_WINDOW_TEX2"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX3, "DECAL_REAR_WINDOW_TEX3"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX4, "DECAL_REAR_WINDOW_TEX4"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX5, "DECAL_REAR_WINDOW_TEX5"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX6, "DECAL_REAR_WINDOW_TEX6"},
    {CARSLOTID_DECAL_REAR_WINDOW_TEX7, "DECAL_REAR_WINDOW_TEX7"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX0, "DECAL_LEFT_DOOR_TEX0"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX1, "DECAL_LEFT_DOOR_TEX1"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX2, "DECAL_LEFT_DOOR_TEX2"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX3, "DECAL_LEFT_DOOR_TEX3"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX4, "DECAL_LEFT_DOOR_TEX4"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX5, "DECAL_LEFT_DOOR_TEX5"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX6, "DECAL_LEFT_DOOR_TEX6"},
    {CARSLOTID_DECAL_LEFT_DOOR_TEX7, "DECAL_LEFT_DOOR_TEX7"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX0, "DECAL_RIGHT_DOOR_TEX0"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX1, "DECAL_RIGHT_DOOR_TEX1"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX2, "DECAL_RIGHT_DOOR_TEX2"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX3, "DECAL_RIGHT_DOOR_TEX3"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX4, "DECAL_RIGHT_DOOR_TEX4"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX5, "DECAL_RIGHT_DOOR_TEX5"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX6, "DECAL_RIGHT_DOOR_TEX6"},
    {CARSLOTID_DECAL_RIGHT_DOOR_TEX7, "DECAL_RIGHT_DOOR_TEX7"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX0, "DECAL_LEFT_QUARTER_TEX0"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX1, "DECAL_LEFT_QUARTER_TEX1"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX2, "DECAL_LEFT_QUARTER_TEX2"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX3, "DECAL_LEFT_QUARTER_TEX3"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX4, "DECAL_LEFT_QUARTER_TEX4"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX5, "DECAL_LEFT_QUARTER_TEX5"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX6, "DECAL_LEFT_QUARTER_TEX6"},
    {CARSLOTID_DECAL_LEFT_QUARTER_TEX7, "DECAL_LEFT_QUARTER_TEX7"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX0, "DECAL_RIGHT_QUARTER_TEX0"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX1, "DECAL_RIGHT_QUARTER_TEX1"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX2, "DECAL_RIGHT_QUARTER_TEX2"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX3, "DECAL_RIGHT_QUARTER_TEX3"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX4, "DECAL_RIGHT_QUARTER_TEX4"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX5, "DECAL_RIGHT_QUARTER_TEX5"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX6, "DECAL_RIGHT_QUARTER_TEX6"},
    {CARSLOTID_DECAL_RIGHT_QUARTER_TEX7, "DECAL_RIGHT_QUARTER_TEX7"},
    {CARSLOTID_WINDOW_TINT, "WINDOW_TINT"},
    {CARSLOTID_CUSTOM_HUD, "CUSTOM_HUD"},
    {CARSLOTID_HUD_BACKING_COLOUR, "HUD_BACKING_COLOUR"},
    {CARSLOTID_HUD_NEEDLE_COLOUR, "HUD_NEEDLE_COLOUR"},
    {CARSLOTID_HUD_CHARACTER_COLOUR, "HUD_CHARACTER_COLOUR"},
    {CARSLOTID_CV, "CV"},
    {CARSLOTID_WHEEL_MANUFACTURER, "WHEEL_MANUFACTURER"},
    {CARSLOTID_MISC, "MISC"},
};

int GetNumCarPartIDNames() {
    return CARPARTID_NUM;
}

const char *GetCarPartNameFromID(int car_part_id) {
    int num_car_part_names = GetNumCarPartIDNames();

    if (car_part_id >= 0 && car_part_id < num_car_part_names) {
        if (CarPartIDNames[car_part_id].CarPartID == car_part_id) {
            return CarPartIDNames[car_part_id].Name;
        }

        for (int i = 0; i < num_car_part_names; i++) {
            if (CarPartIDNames[i].CarPartID == car_part_id) {
                return CarPartIDNames[i].Name;
            }
        }
    }

    return nullptr;
}

int GetCarPartIDFromCrc(UCrc32 crc) {
    int num_car_part_names = GetNumCarPartIDNames();

    for (int i = 0; i < num_car_part_names; i++) {
        if (crc == CarPartIDNames[i].Crc) {
            return CarPartIDNames[i].CarPartID;
        }
    }

    for (unsigned int j = 0; j < 1; j++) {
        if (crc == CarPartIDOldNames[j].Crc) {
            return CarPartIDOldNames[j].CarPartID;
        }
    }

    return CARPARTID_INVALID;
}

int GetNumCarSlotIDNames() {
    return CARSLOTID_NUM;
}

const char *GetCarSlotNameFromID(int car_slot_id) {
    int num_car_slot_names = GetNumCarSlotIDNames();

    if (car_slot_id >= 0 && car_slot_id < num_car_slot_names) {
        if (CarSlotIDNames[car_slot_id].CarSlotID == car_slot_id) {
            return CarSlotIDNames[car_slot_id].Name;
        }

        for (int i = 0; i < num_car_slot_names; i++) {
            if (CarSlotIDNames[i].CarSlotID == car_slot_id) {
                return CarSlotIDNames[i].Name;
            }
        }
    }

    return nullptr;
}
