#ifndef WORLD_CARRENDER_H
#define WORLD_CARRENDER_H

#ifdef EA_PRAGMA_ONCE_SUPPORTED
#pragma once
#endif

enum CarEffectPosition {
    CARFXPOS_NONE,
    CARFXPOS_FRONT_TIRES,
    CARFXPOS_REAR_TIRES,
    CARFXPOS_LEFT_TIRES,
    CARFXPOS_RIGHT_TIRES,
    CARFXPOS_TIRE_FL,
    CARFXPOS_TIRE_FR,
    CARFXPOS_TIRE_RR,
    CARFXPOS_TIRE_RL,
    CARFXPOS_ENGINE,
    CARFXPOS_EXHAUST,
    CARFXPOS_RADIATOR,
    CARFXPOS_WINDSHIELD,
    CARFXPOS_WINDOW_REAR,
    CARFXPOS_WINDOW_LEFT_FRONT,
    CARFXPOS_WINDOW_LEFT_REAR,
    CARFXPOS_WINDOW_RIGHT_FRONT,
    CARFXPOS_WINDOW_RIGHT_REAR,
    CARFXPOS_HEADLIGHT,
    CARFXPOS_HEADLIGHT_LEFT,
    CARFXPOS_HEADLIGHT_RIGHT,
    CARFXPOS_BRAKELIGHT,
    CARFXPOS_BRAKELIGHT_LEFT,
    CARFXPOS_BRAKELIGHT_RIGHT,
    CARFXPOS_SIDE_MIRROR_LEFT,
    CARFXPOS_SIDE_MIRROR_RIGHT,
    CARFXPOS_LICENSE_PLATE_FRONT,
    CARFXPOS_LICENSE_PLATE_REAR,
    NUM_CARFXPOS,
};

struct CarFXPosInfo {
    // Members
    unsigned int position_marker_hashes[4]; // offset 0x0, size 0x10
    unsigned char marker_count; // offset 0x10, size 0x1
};

void InitCarEffects();
void CloseCarEffects();

#endif
