#ifndef INPUT_ACTION_DATA_H
#define INPUT_ACTION_DATA_H

#ifdef EA_PRAGMA_ONCE_SUPPORTED
#pragma once
#endif

enum ActionID {
    MAX_ACTIONID = 138,
    ACTION_FLUSH = 137,
    ACTION_UNPLUGGED = 136,
    ACTION_PLUGGED = 135,
    ACTION_EXITAPPLICATION = 134,
    ICEACTION_SHUTTLE_SPEED_INC = 133,
    ICEACTION_SHUTTLE_SPEED_DEC = 132,
    ICEACTION_SHUTTLE_DOWN = 131,
    ICEACTION_SHUTTLE_UP = 130,
    ICEACTION_SHUTTLE_RIGHT = 129,
    ICEACTION_SHUTTLE_LEFT = 128,
    ICEACTION_SHAKE_FRQ_INC = 127,
    ICEACTION_SHAKE_FRQ_DEC = 126,
    ICEACTION_SHAKE_MAG_INC = 125,
    ICEACTION_SHAKE_MAG_DEC = 124,
    ICEACTION_BUBBLE_FORTH = 123,
    ICEACTION_BUBBLE_BACK = 122,
    ICEACTION_BUBBLE_RIGHT = 121,
    ICEACTION_BUBBLE_LEFT = 120,
    ICEACTION_BUBBLE_SPIN_RIGHT = 119,
    ICEACTION_BUBBLE_SPIN_LEFT = 118,
    ICEACTION_BUBBLE_TILT_DOWN = 117,
    ICEACTION_BUBBLE_TILT_UP = 116,
    ICEACTION_BUBBLE_DOWN = 115,
    ICEACTION_BUBBLE_UP = 114,
    ICEACTION_BUBBLE_OUT = 113,
    ICEACTION_BUBBLE_IN = 112,
    ICEACTION_LETTERBOX_OUT = 111,
    ICEACTION_LETTERBOX_IN = 110,
    ICEACTION_ZOOM_OUT = 109,
    ICEACTION_ZOOM_IN = 108,
    ICEACTION_DUTCH_RIGHT = 107,
    ICEACTION_DUTCH_LEFT = 106,
    ICEACTION_SIMSPEED_DEC = 105,
    ICEACTION_SIMSPEED_INC = 104,
    ICEACTION_CLIP_OUT = 103,
    ICEACTION_CLIP_IN = 102,
    ICEACTION_ALT_1 = 101,
    ICEACTION_CANCEL = 100,
    ICEACTION_SELECT = 99,
    ICEACTION_PASTE = 98,
    ICEACTION_COPY = 97,
    ICEACTION_CUT = 96,
    ICEACTION_INSERT = 95,
    ICEACTION_SCREENSHOT_STREAM = 94,
    ICEACTION_SCREENSHOT = 93,
    ICEACTION_HIDE = 92,
    ICEACTION_PLAY = 91,
    ICEACTION_UNDO = 90,
    ICEACTION_HELP = 89,
    ICEACTION_DOWN = 88,
    ICEACTION_UP = 87,
    ICEACTION_FAST_RIGHT = 86,
    ICEACTION_FAST_LEFT = 85,
    ICEACTION_RIGHT = 84,
    ICEACTION_LEFT = 83,
    ICEACTION_GRAB_RIGHT = 82,
    ICEACTION_GRAB_LEFT = 81,
    DEBUGACTION_TOGGLEDEMOCAMERAS = 80,
    DEBUGACTION_TOGGLECARCOLOUR = 79,
    DEBUGACTION_STOPRECORDPATH = 78,
    DEBUGACTION_SCREENSHOT = 77,
    DEBUGACTION_SIMSTEP = 76,
    DEBUGACTION_TOGGLESIMSTEP = 75,
    DEBUGACTION_TOGGLEAI = 74,
    DEBUGACTION_DROPCAR = 73,
    DEBUGACTION_SUPER_TURBO = 72,
    DEBUGACTION_TURBO = 71,
    DEBUGACTION_LOOK_D_RIGHT = 70,
    DEBUGACTION_LOOK_D_LEFT = 69,
    DEBUGACTION_LOOK_D_DOWN = 68,
    DEBUGACTION_LOOK_D_UP = 67,
    DEBUGACTION_LOOK_RIGHT = 66,
    DEBUGACTION_LOOK_LEFT = 65,
    DEBUGACTION_LOOK_DOWN = 64,
    DEBUGACTION_LOOK_UP = 63,
    DEBUGACTION_MOVE_D_BACK = 62,
    DEBUGACTION_MOVE_D_FORWARD = 61,
    DEBUGACTION_MOVE_D_RIGHT = 60,
    DEBUGACTION_MOVE_D_LEFT = 59,
    DEBUGACTION_MOVE_BACK = 58,
    DEBUGACTION_MOVE_FORWARD = 57,
    DEBUGACTION_MOVE_RIGHT = 56,
    DEBUGACTION_MOVE_LEFT = 55,
    DEBUGACTION_MOVE_DOWN = 54,
    DEBUGACTION_MOVE_UP = 53,
    VOIPACTION_PUSHTOTALK = 52,
    HUDACTION_NEXTSONG = 51,
    HUDACTION_SKIPNIS = 50,
    HUDACTION_PAD_RIGHT = 49,
    HUDACTION_PAD_DOWN = 48,
    HUDACTION_PAD_LEFT = 47,
    HUDACTION_ENGAGE_EVENT = 46,
    HUDACTION_PAUSEREQUEST = 45,
    FRONTENDACTION_RTRIGGER = 44,
    FRONTENDACTION_LTRIGGER = 43,
    FRONTENDACTION_BUTTON5 = 42,
    FRONTENDACTION_BUTTON4 = 41,
    FRONTENDACTION_BUTTON3 = 40,
    FRONTENDACTION_BUTTON2 = 39,
    FRONTENDACTION_BUTTON1 = 38,
    FRONTENDACTION_BUTTON0 = 37,
    FRONTENDACTION_START = 36,
    FRONTENDACTION_CANCEL_ALT = 35,
    FRONTENDACTION_CANCEL = 34,
    FRONTENDACTION_ACCEPT = 33,
    FRONTENDACTION_RRIGHT = 32,
    FRONTENDACTION_RLEFT = 31,
    FRONTENDACTION_RDOWN = 30,
    FRONTENDACTION_RUP = 29,
    FRONTENDACTION_RIGHT = 28,
    FRONTENDACTION_LEFT = 27,
    FRONTENDACTION_DOWN = 26,
    FRONTENDACTION_UP = 25,
    CAMERAACTION_PULLBACK = 24,
    CAMERAACTION_LOOKBACK = 23,
    CAMERAACTION_ENABLE_ICE = 22,
    CAMERAACTION_DEBUG = 21,
    CAMERAACTION_CHANGE = 20,
    GAMEACTION_DEBUGHUMAN4 = 19,
    GAMEACTION_DEBUGHUMAN3 = 18,
    GAMEACTION_DEBUGHUMAN2 = 17,
    GAMEACTION_DEBUGHUMAN1 = 16,
    GAMEACTION_JUMP = 15,
    GAMEACTION_BACK = 14,
    GAMEACTION_FORWARD = 13,
    GAMEACTION_RESET = 12,
    GAMEACTION_NOS = 11,
    GAMEACTION_SHIFTDOWN = 10,
    GAMEACTION_SHIFTUP = 9,
    GAMEACTION_GAMEBREAKER = 8,
    GAMEACTION_HANDBRAKE = 7,
    GAMEACTION_BRAKE = 6,
    GAMEACTION_GAS = 5,
    GAMEACTION_TURNRIGHT = 4,
    GAMEACTION_TURNLEFT = 3,
    GAMEACTION_STEERRIGHT = 2,
    GAMEACTION_STEERLEFT = 1,
    NULL_ACTION = 0,
};

// total size: 0xC
class ActionData {
  public:
    // bool IsNull() const {}

    int Slot() const {
        return this->slot;
    }

    void SetID(int id) {
        this->id = id;
    }

    void SetData(float d) {
        this->data = d;
    }

    void SetSlot(int slot) {
        this->slot = slot;
    }

    int ID() const {
        return this->id;
    }

    float Data() const {
        return this->data;
    }

  private:
    int id;     // offset 0x0, size 0x4
    int slot;   // offset 0x4, size 0x4
    float data; // offset 0x8, size 0x4
};

#endif
