# Splat config for SLES-53558-A124 (PS2)
name: Need for Speed Most Wanted A124 PS2 Prototype
sha1: d01ad0bca1f88e1261cfaba35fccdbb8fba38d80

options:
  basename: NSF.ELF
  target_path: orig/SLES-53558-A124/NFS.ELF
  elf_path: build/SLES-53558-A124/NFS.ELF
  base_path: ../..
  platform: ps2
  compiler: EEGCC

  # Output paths
  asm_path: build/SLES-53558-A124/asm
  src_path: src
  build_path: build/SLES-53558-A124/obj

  # Assembly options
  generate_asm_macros_files: True
  named_regs_for_c_funcs: False
  find_file_boundaries: False
  disasm_unknown: True

  # Rodata options
  rodata_string_guesser_level: 0 # improve string detection
  suggestion_rodata_section_start: True
  pair_rodata_to_text: False
  migrate_rodata_to_functions: True

  # Auto-generate undefined functions and symbols
  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/SLES-53558-A124//undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/SLES-53558-A124//undefined_syms_auto.txt

  # Manually defined symvols
  symbol_addrs_path: config/SLES-53558-A124/symbols.txt
  ld_script_path: build/SLES-53558-A124/ldscript.ld

  # ELF sections
  section_order: [".text", ".vutext", ".noover", ".rodata", ".gcc_except_table", ".over", ".data", ".lit4", ".sdata", ".sbss", ".bss"]
  auto_link_sections: [".rodata", ".data", ".lit4", ".sdata", ".sbss", ".bss"]

  # Linker script options
  subalign: 8

  # TODO gp_value

segments:
  # - [0, databin, elf_header]

  - name: main
    type: code
    start: 0x001000
    vram: 0x100000
    bss_size: 0x374dc
    subsegments:
    # - [0x1000, asmtu, Speed/Indep/SourceLists/zAI.cpp]
    - [0x45728, asmtu, Speed/Indep/SourceLists/zAnim.cpp]
    # - [0x50A78, asmtu, Speed/Indep/SourceLists/zAttribSys.cpp]
    # - [0x5BE08, asmtu, Speed/Indep/SourceLists/zBWare.cpp]
    - [0x65F70, asmtu, Speed/Indep/SourceLists/zCamera.cpp]
    - [0x83EC4, asmtu, Speed/Indep/SourceLists/zComms.cpp]
    - [0x83EC8, asmtu, Speed/Indep/SourceLists/zDebug.cpp]
    - [0x878B0, asmtu, Speed/Indep/SourceLists/zDynamics.cpp]
    - [0x8E320, asmtu, Speed/Indep/SourceLists/zEagl4Anim.cpp]
    - [0xA7B60, asmtu, Speed/Indep/SourceLists/zEAXSound.cpp]
    - [0xCC4F8, asmtu, Speed/Indep/SourceLists/zEAXSound2.cpp]
    # - [0xF4F00, asmtu, Speed/Indep/SourceLists/zEcstasy.cpp]
    - [0x12A778, asmtu, Speed/Indep/SourceLists/zFe.cpp]
    - [0x185098, asmtu, Speed/Indep/SourceLists/zFe2.cpp]
    - [0x1C50C8, asmtu, Speed/Indep/SourceLists/zFEng.cpp]
    # - [0x1D8910, asmtu, Speed/Indep/SourceLists/zFoundation.cpp]
    - [0x1E0538, asmtu, Speed/Indep/SourceLists/zGameModes.cpp]
    - [0x1E0990, asmtu, Speed/Indep/SourceLists/zGameplay.cpp]
    # - [0x204800, asmtu, Speed/Indep/SourceLists/zLua.cpp]
    - [0x21C228, asmtu, Speed/Indep/SourceLists/zMain.cpp]
    # - [0x246EB8, asmtu, Speed/Indep/SourceLists/zMisc.cpp]
    - [0x2641F8, asmtu, Speed/Indep/SourceLists/zMiscSmall.cpp]
    - [0x2644A8, asmtu, Speed/Indep/SourceLists/zMission.cpp]
    # - [0x2644D8, asmtu, Speed/Indep/SourceLists/zPhysics.cpp]
    # - [0x2877C8, asmtu, Speed/Indep/SourceLists/zPhysicsBehaviors.cpp]
    - [0x2BFEB8, asmtu, Speed/Indep/SourceLists/zPlatform.cpp]
    - [0x2CC6E8, asmtu, Speed/Indep/SourceLists/zRender.cpp]
    - [0x2CC7B0, asmtu, Speed/Indep/SourceLists/zSim.cpp]
    - [0x2E5D00, asmtu, Speed/Indep/SourceLists/zSpeech.cpp]
    - [0x310930, asmtu, Speed/Indep/SourceLists/zTrack.cpp]
    # - [0x3234D0, asmtu, Speed/Indep/SourceLists/zWorld.cpp]
    - [0x357EE8, asmtu, Speed/Indep/SourceLists/zWorld2.cpp]

    - [0x435C90, pad, rest]

    # - [0x435D60, pad, idk]

    # - [0x4397B0, asmtu, Speed/Indep/SourceLists/zOnline]
    # - [0x4B50C0, asmtu, Speed/Indep/SourceLists/zFeOverlay]

    # TODO
    # - [0x4D7D50, pad, rest]

    # - [0x113e00, data]

    # - [0x192d00, rodata]

  # - [0x1A1C70, databin]
  - [0x68c4db]
