#include "Speed/Indep/Src/EAXSound/EAXSoundEnums.hpp"

int RoadNoiseVolumes[MAX_NUM_FXROADNOISE_LOOP] = {
    15000, // FXROADNOISE_LOOP_GRAVEL00
    24000, // FXROADNOISE_LOOP_SIDEWALK
    32000, // FXROADNOISE_LOOP_COBBLESTONE00
    24000, // FXROADNOISE_LOOP_DEEPWATER
    24000, // FXROADNOISE_LOOP_WETROAD
    12000, // FXROADNOISE_LOOP_ASHPHALT00
    19000, // FXROADNOISE_LOOP_ASHPHALT01
    32500, // FXROADNOISE_LOOP_METAL
    32500, // FXROADNOISE_LOOP_STITCH_LOOP
};

int GetRoadNoiseTransitionVol(FXROADNOISE_TRANSITION ID) {
    switch (ID) {
        case FXROADNOISE_TRANSITION_CURBON:
            return 15500;
        case FXROADNOISE_TRANSITION_CURBOFF:
            return 15500;
        case FXROADNOISE_TRANSITION_SPIKESTRIP:
            return 26000;
        case FXROADNOISE_TRANSITION_BLOWN:
            return 32767;
    }
    return 32767;
}
