#ifndef _EMSYSTYPES_H_PARTICLE_ANIMATION
#define _EMSYSTYPES_H_PARTICLE_ANIMATION

enum EffectParticleAnimation {
    ANIMATE_PARTICLE_NONE = 0,
    ANIMATE_PARTICLE_2x2 = 2,
    ANIMATE_PARTICLE_4x4 = 4,
    ANIMATE_PARTICLE_8x8 = 8,
    ANIMATE_PARTICLE_16x16 = 16,
};

#endif
