#ifndef _EMSYSTYPES_H_CONSTRAINTS
#define _EMSYSTYPES_H_CONSTRAINTS

enum EffectParticleConstraint {
    CONSTRAIN_PARTICLE_NONE = 0,
    CONSTRAIN_PARTICLE_XY_AXIS = 6,
    CONSTRAIN_PARTICLE_XZ_AXIS = 5,
    CONSTRAIN_PARTICLE_YZ_AXIS = 3,
    CONSTRAIN_PARTICLE_CAMERA = 8,
};

#endif
