#!/usr/bin/env python3

###
# Splits the ELF according to the config.yml and generates a config.json based on it
#
# Usage:
#   python3 tools/delink_to_config_json.py config/VERSION/config.yml build/VERSION
###

import argparse
from pathlib import Path
import subprocess
import json
import yaml


def generate_config_json(delink_path: Path, config_yml: Path, build_folder: Path) -> tuple[str, list[str]]:
    with config_yml.open("r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    target_path = config["target_path"]
    splits_path = config["splits_path"]
    symbols_path = config["symbols_path"]
    splits = config["splits"]
    with Path(splits_path).open("r", encoding="utf-8") as f:
        object_splits = json.load(f)
    
    delink_args = [
        delink_path.as_posix(),
        "ida-split",
        symbols_path,
        target_path,
        "--idapro",
        splits_path,
        "-o",
        (build_folder / "obj").as_posix(),
    ]

    subprocess.run(delink_args, check=True)


    config_json = {
        "version": "1.7.0",
        "name": "main",
        "module_id": 0,  # TODO for rels
        "ldscript": (build_folder / "ldscript.ld").as_posix(),
        "entry": "__start",  # TODO
        "units": [],
        "linker_inputs": [],
        "extract": [],
        "modules": [],
        "links": [],
    }

    source_objects = {Path(split).with_suffix(".obj").as_posix(): split for split in splits}
    for obj_name in object_splits:
        src_path = source_objects.get(obj_name)
        config_json["units"].append(
            {
                "object": (build_folder / "obj" / obj_name).as_posix(),
                "name": src_path or obj_name,
                "autogenerated": src_path is None,
                "code_size": 0,  # these are not needed
                "data_size": 0,
            }
        )

    config_json["linker_inputs"] = [
        (build_folder / "obj" / filename).as_posix()
        for filename in ("__pe_resources.res", "__except_list.obj")
    ]

    return json.dumps(config_json), [target_path, splits_path, symbols_path]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="""Splits the configured binary and generates a config.json"""
    )
    parser.add_argument(
        "delink_path",
        help="""Path to the delink executable""",
    )
    parser.add_argument(
        "yml_file",
        help="""Config yml in""",
    )
    parser.add_argument(
        "build_folder",
        help="""Build folder out""",
    )
    args = parser.parse_args()

    build_folder = Path(args.build_folder)
    config_path = build_folder / "config.json"
    output, dependencies = generate_config_json(
        Path(args.delink_path), Path(args.yml_file), build_folder
    )

    with config_path.open("w", encoding="UTF-8") as f:
        f.write(output)

    def dep_path(path: str | Path) -> str:
        return str(path).replace("\\", "/").replace(" ", "\\ ")

    with (build_folder / "dep").open("w", encoding="UTF-8") as f:
        f.write(f"{dep_path(config_path)}: {' '.join(map(dep_path, dependencies))}\n")


if __name__ == "__main__":
    main()
