//
//
//
//
//
//
#ifndef SNDFILEIOENUMS_HPP
#define SNDFILEIOENUMS_HPP

// Decl: 16
enum eSNDDATAPATH {
    SNDPATH_ROUTE = 0,
    SNDPATH_ENGINE = 1,
    SNDPATH_EVTSYS = 2,
    SNDPATH_FE = 3,
    SNDPATH_GLOBAL = 4,
    SNDPATH_INGAME = 5,
    SNDPATH_NOS = 6,
    SNDPATH_PATHFINDER = 7,
    SNDPATH_SKIDS = 8,
    SNDPATH_SPEECH = 9,
    SNDPATH_TURBO = 10,
    SNDPATH_SHIFT = 11,
    SNDPATH_FXEDIT = 12,
    MAX_SNDDATA_PATHS = 13,
};

// Decl: 59
enum eSNDDATATYPE {
    SDT_NONE = -1,
    SDT_AEMS_AUDIOMEM = 0,
    SDT_AEMS_MAINMEM = 1,
    SDT_AEMS_SYNCSPU = 2,
    SDT_AEMS_ASYNCSPU = 3,
    SDT_AEMS_ASYNCSPUMEM = 4,
    SDT_GENERIC_DATA = 5,
};

// Decl: 74
enum eTEMPALLOCLOCATION {
    TMP_ALLOC_NONE = 0,
    TMP_ALLOC_MAIN = 1,
    TMP_ALLOC_TRACKSTREAMER = 2,
    TMP_ALLOC_AUDIO = 3,
};

#endif
