name: Build

on:
  push:
  pull_request:

jobs:
  build:
    # This is a *private* build container.
    # See docs/github_actions.md for more information.
    container: ghcr.io/dbalatoni13/nfs-gc-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Add game versions here
        version: [GOWE69, EUROPEGERMILESTONE, SLES-53558-A124]

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Install dependencies
      if: ${{ matrix.version == 'SLES-53558-A124' }}
      run: pip install --break-system-packages -r requirements.txt

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /orig .

    # Build the project
    - name: Build
      run: |
        # Select binutils path based on version index
        if [[ "${{ matrix.version }}" == 'SLES-53558-A124' ]]; then
          BINUTILS="/mips_binutils"
        else
          BINUTILS="/ppc_binutils"
        fi

        python configure.py --map --version ${{ matrix.version }} \
            --binutils "$BINUTILS" --compilers /compilers
        ninja all_source progress build/${{ matrix.version }}/report.json

    # Upload map files
    - name: Upload map
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_maps
        path: build/${{ matrix.version }}/**/*.MAP

    # Upload progress report
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/report.json
